import type { LanguageTarget } from '../../engine/types';

/**
 * Language targets B1 → C2. The world never announces them; missions, retrieval
 * moments and the training room are tagged with them, and the player's language
 * model tracks each one.
 */
export const TARGETS: LanguageTarget[] = [
  // ---------------------------------------------------------------- B1 foundations
  {
    id: 'w-fragen',
    label: 'W-Fragen & Fragesatzstellung',
    level: 'B1',
    category: 'syntax',
    explanation: 'In W-Fragen steht das Verb direkt nach dem Fragewort: „Von welchem Gleis fährt die S5?“',
    pl: 'Po zaimku pytającym od razu czasownik.',
    examples: ['Wo fährt die S5 ab?', 'Von welchem Gleis fährt der Zug?'],
  },
  {
    id: 'v2-inversion',
    label: 'Verbzweitstellung (Inversion)',
    level: 'B1',
    category: 'wordOrder',
    explanation: 'Im Hauptsatz steht das konjugierte Verb an Position 2. Steht etwas anderes vorne, kommt das Subjekt nach dem Verb: „Heute komme ich später.“',
    pl: 'Czasownik zawsze na drugim miejscu. „Heute ich komme“ jest błędem.',
    examples: ['Morgen fange ich an.', 'Leider habe ich keine Zeit.'],
  },
  {
    id: 'nebensatz-verbend',
    label: 'Verbendstellung im Nebensatz',
    level: 'B1',
    category: 'wordOrder',
    explanation: 'Nach weil, dass, ob, wenn, obwohl steht das konjugierte Verb am Ende: „…, weil der Zug Verspätung hat.“',
    pl: 'W zdaniu podrzędnym czasownik na końcu.',
    examples: ['Ich weiß nicht, ob der Zug pünktlich ist.', 'Ich komme später, weil die S-Bahn ausfällt.'],
  },
  {
    id: 'dativ-praep',
    label: 'Präpositionen mit Dativ',
    level: 'B1',
    category: 'cases',
    explanation: 'aus, bei, mit, nach, seit, von, zu, gegenüber verlangen immer den Dativ: „mit dem Zug“, „zur Arbeit“, „von welchem Gleis“.',
    pl: 'Te przyimki zawsze łączą się z celownikiem (Dativ).',
    examples: ['Ich fahre mit der S-Bahn zum Alexanderplatz.', 'Seit einem Jahr lerne ich intensiv.'],
  },
  {
    id: 'akk-praep',
    label: 'Präpositionen mit Akkusativ',
    level: 'B1',
    category: 'cases',
    explanation: 'durch, für, gegen, ohne, um verlangen den Akkusativ: „für den Vertrag“, „ohne einen Termin“.',
    pl: 'Te przyimki zawsze z biernikiem (Akkusativ).',
    examples: ['Das ist für den Mandanten.', 'Ohne einen Termin geht es nicht.'],
  },
  {
    id: 'wechselpraep',
    label: 'Wechselpräpositionen (Wo? / Wohin?)',
    level: 'B1',
    category: 'prepositions',
    explanation: 'in, an, auf, über, unter, vor, hinter, neben, zwischen: Wohin? → Akkusativ, Wo? → Dativ. „Ich gehe ins Büro“ / „Ich bin im Büro“.',
    pl: 'Kierunek = Akkusativ, miejsce = Dativ.',
    examples: ['Ich lege den Vertrag auf den Tisch.', 'Der Vertrag liegt auf dem Tisch.'],
  },
  {
    id: 'perfekt-sein',
    label: 'Perfekt mit „sein“',
    level: 'B1',
    category: 'tense',
    explanation: 'Verben der Bewegung und Zustandsveränderung bilden das Perfekt mit „sein“: „Ich bin angekommen“, „Wir sind umgestiegen“.',
    pl: 'Czasowniki ruchu i zmiany stanu: Perfekt z „sein“.',
    examples: ['Ich bin heute Morgen angekommen.', 'Was ist passiert?'],
  },
  {
    id: 'genus',
    label: 'Genus der Nomen',
    level: 'B1',
    category: 'gender',
    explanation: 'Jedes Nomen hat ein festes Genus. Lernen Sie Nomen immer mit Artikel: das Gleis, der Vertrag, die Kaution.',
    pl: 'Rodzaj rzeczowników niemieckich często nie pokrywa się z polskim.',
    examples: ['das Gleis', 'der Vertrag', 'die Frist'],
  },
  {
    id: 'hoeflichkeit-k2',
    label: 'Höflichkeit mit Konjunktiv II',
    level: 'B1',
    category: 'register',
    explanation: '„Könnten Sie…?“, „Ich hätte gern…“, „Würden Sie…?“ klingen höflich und natürlich. „Ich will…“ wirkt im Service-Kontext fordernd.',
    pl: 'Tryb przypuszczający = uprzejmość. „Ich will“ brzmi roszczeniowo.',
    examples: ['Könnten Sie mir sagen, wo …?', 'Ich hätte gern einen Cappuccino.'],
  },
  {
    id: 'du-sie',
    label: 'Anrede: du oder Sie',
    level: 'B1',
    category: 'register',
    explanation: 'Fremde, Behörden, Vorgesetzte: „Sie“. Kolleginnen und Kollegen im Team oft „du“ – aber erst, wenn es angeboten wird.',
    pl: '„Sie“ wobec obcych i przełożonych; „du“ dopiero po propozycji.',
    examples: ['Können Sie mir helfen?', 'Kannst du mir kurz helfen?'],
  },
  {
    id: 'trennbare-verben',
    label: 'Trennbare Verben',
    level: 'B1',
    category: 'syntax',
    explanation: 'Das Präfix geht ans Satzende: „Ich steige am Alexanderplatz um.“ Im Nebensatz bleibt das Verb zusammen: „…, wo ich umsteige.“',
    pl: 'Przedrostek rozdzielny idzie na koniec zdania.',
    examples: ['Der Zug fährt um 7:12 ab.', 'Rufen Sie mich bitte zurück.'],
  },
  {
    id: 'uhrzeit',
    label: 'Uhrzeiten & Termine',
    level: 'B1',
    category: 'vocabulary',
    explanation: 'Offiziell: „um vierzehn Uhr dreißig“. Umgangssprachlich: „um halb drei“ (= 14:30!).',
    pl: '„halb drei“ = 14:30, nie 15:30.',
    examples: ['Der Termin ist um halb drei.', 'Wir treffen uns um Viertel nach acht.'],
  },
  {
    id: 'adj-endungen',
    label: 'Adjektivendungen',
    level: 'B1+',
    category: 'adjectiveEndings',
    explanation: 'Die Endung zeigt Kasus und Genus: „mit dem neuen Vertrag“, „einen schwarzen Kaffee“, „bei gutem Wetter“.',
    pl: 'Końcówka przymiotnika zależy od rodzajnika, przypadku i rodzaju.',
    examples: ['Ich hätte gern einen großen Milchkaffee.', 'Das ist ein wichtiger Termin.'],
  },
  {
    id: 'relativsatz',
    label: 'Relativsätze',
    level: 'B1+',
    category: 'syntax',
    explanation: 'Das Relativpronomen richtet sich im Genus nach dem Bezugswort, im Kasus nach seiner Funktion im Nebensatz: „der Vertrag, den ich prüfe“.',
    pl: 'Zaimek względny: rodzaj od rzeczownika, przypadek od funkcji w zdaniu podrzędnym.',
    examples: ['Das ist die Klausel, über die wir gesprochen haben.', 'Der Spieler, dessen Vertrag ausläuft, …'],
  },
  {
    id: 'modalverben-perfekt',
    label: 'Modalverben in der Vergangenheit',
    level: 'B1+',
    category: 'tense',
    explanation: 'Meist Präteritum: „Ich musste umsteigen“, „Ich konnte nicht kommen“.',
    examples: ['Ich musste zweimal umsteigen.', 'Wir konnten den Vertrag noch nicht prüfen.'],
  },
  // ---------------------------------------------------------------- B2
  {
    id: 'gen-prep',
    label: 'wegen / trotz / während + Genitiv',
    level: 'B2',
    category: 'cases',
    explanation: 'In der Standard- und Schriftsprache: „wegen des Streiks“, „trotz der Verspätung“, „während der Besprechung“. „wegen dem“ ist umgangssprachlich – im Beruf vermeiden.',
    pl: 'W języku pisanym i zawodowym: dopełniacz (Genitiv).',
    examples: ['Wegen des Streiks fällt die S-Bahn aus.', 'Trotz der kurzen Frist ist die Prüfung vollständig.'],
  },
  {
    id: 'passiv',
    label: 'Passiv (Vorgangs- & Zustandspassiv)',
    level: 'B2',
    category: 'grammar',
    explanation: '„Der Vertrag wird geprüft“ (Vorgang) vs. „Der Vertrag ist geprüft“ (Zustand). Mit Modalverb: „muss geprüft werden“.',
    pl: 'Strona bierna: werden + Partizip II; stan: sein + Partizip II.',
    examples: ['Der Vertrag muss heute noch geprüft werden.', 'Die Frist ist bereits abgelaufen.'],
  },
  {
    id: 'konj2-vergangenheit',
    label: 'Konjunktiv II der Vergangenheit',
    level: 'B2',
    category: 'grammar',
    explanation: '„Wenn ich das gewusst hätte, wäre ich früher gekommen.“',
    examples: ['Hätten Sie mich angerufen, wäre ich sofort gekommen.'],
  },
  {
    id: 'n-deklination',
    label: 'n-Deklination',
    level: 'B2',
    category: 'cases',
    explanation: 'Einige maskuline Nomen bekommen außer im Nominativ -(e)n: „den Mandanten“, „dem Kollegen“, „des Juristen“.',
    pl: 'Niektóre rzeczowniki męskie mają końcówkę -(e)n we wszystkich przypadkach poza mianownikiem.',
    examples: ['Ich spreche mit dem Mandanten.', 'Fragen Sie den Kollegen.'],
  },
  {
    id: 'verb-praep',
    label: 'Verben mit Präpositionen',
    level: 'B2',
    category: 'prepositions',
    explanation: 'sich kümmern um, bestehen auf, hinweisen auf, sich beziehen auf, verzichten auf … Die Präposition ist fest.',
    pl: 'Rekcja czasowników – przyimek jest stały i trzeba go znać.',
    examples: ['Ich kümmere mich um den Vertrag.', 'Ich möchte Sie auf § 7 hinweisen.'],
  },
  {
    id: 'infinitiv-zu',
    label: 'Infinitiv mit „zu“',
    level: 'B2',
    category: 'syntax',
    explanation: '„Es ist wichtig, die Frist einzuhalten.“ Bei trennbaren Verben steht „zu“ in der Mitte.',
    examples: ['Ich habe vor, morgen anzufangen.', 'Vergessen Sie nicht, den Vertrag zu unterschreiben.'],
  },
  {
    id: 'konnektoren',
    label: 'Konnektoren & Textkohärenz',
    level: 'B2',
    category: 'writing',
    explanation: 'Zusammenhänge sichtbar machen: allerdings, dennoch, folglich, zudem, während, wohingegen.',
    examples: ['Die Summe ist korrekt; allerdings fehlt die Frist.'],
  },
  {
    id: 'email-register',
    label: 'Berufliche E-Mails',
    level: 'B2',
    category: 'professional',
    explanation: 'Anrede („Sehr geehrte Frau Dr. Kessler“ / „Liebe Frau Kessler“), klare Struktur, Grußformel („Mit freundlichen Grüßen“ / „Beste Grüße“).',
    pl: 'Konwencje e-maila biznesowego.',
    examples: ['Sehr geehrte Frau Kessler,', 'Mit freundlichen Grüßen'],
  },
  {
    id: 'nominalstil',
    label: 'Nominalstil',
    level: 'B2+',
    category: 'professional',
    explanation: 'Fachsprache verdichtet Verben zu Nomen: „nach Prüfung des Vertrags“ statt „nachdem wir den Vertrag geprüft haben“.',
    examples: ['Nach Unterzeichnung des Vertrags …', 'Bei Nichteinhaltung der Frist …'],
  },
  {
    id: 'funktionsverbgefuege',
    label: 'Funktionsverbgefüge',
    level: 'B2+',
    category: 'collocation',
    explanation: 'Feste Verbindungen: in Kraft treten, zur Verfügung stellen, in Frage kommen, Bezug nehmen auf, eine Entscheidung treffen.',
    pl: 'Stałe połączenia rzeczownik + czasownik – nie tłumaczyć dosłownie.',
    examples: ['Der Vertrag tritt am 1. Juli in Kraft.', 'Wir stellen Ihnen die Unterlagen zur Verfügung.'],
  },
  {
    id: 'kollokationen',
    label: 'Kollokationen',
    level: 'B2+',
    category: 'collocation',
    explanation: 'Welche Wörter zusammengehören: eine Frist einhalten / setzen / verlängern, einen Vertrag schließen / kündigen, Bedenken äußern.',
    examples: ['Wir müssen die Frist einhalten.', 'Ich möchte Bedenken äußern.'],
  },
  // ---------------------------------------------------------------- C1
  {
    id: 'konj1-redewiedergabe',
    label: 'Konjunktiv I (indirekte Rede)',
    level: 'C1',
    category: 'grammar',
    explanation: 'In Berichten und Protokollen: „Der Berater erklärte, die Summe sei korrekt.“',
    examples: ['Der Verein teilte mit, man habe die Klausel geprüft.'],
  },
  {
    id: 'partizipialattribut',
    label: 'Erweiterte Partizipialattribute',
    level: 'C1',
    category: 'syntax',
    explanation: '„der von beiden Parteien unterzeichnete Vertrag“ – typisch für Rechts- und Wirtschaftstexte.',
    examples: ['die am 30. Juni ablaufende Frist', 'die vom Spieler geforderte Summe'],
  },
  {
    id: 'modalpartikeln',
    label: 'Modalpartikeln',
    level: 'C1',
    category: 'idioms',
    explanation: 'doch, ja, mal, eben, halt, wohl – sie tragen Einstellung und Ton: „Das ist ja interessant.“ „Kommen Sie doch rein.“',
    examples: ['Schauen Sie sich das doch mal an.', 'Das ist halt so in Berlin.'],
  },
  {
    id: 'register-wechsel',
    label: 'Registerwechsel',
    level: 'C1',
    category: 'register',
    explanation: 'Denselben Inhalt passend für Freund, Kollegin, Mandant oder Gericht formulieren.',
    examples: ['„Das klappt nicht.“ → „Dies ist leider nicht umsetzbar.“'],
  },
  {
    id: 'argumentation',
    label: 'Argumentieren & Stellung nehmen',
    level: 'C1',
    category: 'professional',
    explanation: 'Position – Begründung – Beleg – Einwand – Schluss. Redemittel: „Ausschlaggebend ist …“, „Dem ist entgegenzuhalten, dass …“',
    examples: ['Ausschlaggebend ist aus meiner Sicht § 7 Abs. 2.'],
  },
  {
    id: 'verhandeln',
    label: 'Verhandeln',
    level: 'C1',
    category: 'professional',
    explanation: 'Vorschläge relativieren, Zugeständnisse an Bedingungen knüpfen: „Wir könnten uns vorstellen, …, vorausgesetzt, dass …“',
    examples: ['Wir wären bereit, … sofern …'],
  },
  // ---------------------------------------------------------------- C2 / legal / translation
  {
    id: 'juristendeutsch',
    label: 'Juristendeutsch lesen',
    level: 'C1+',
    category: 'professional',
    explanation: 'Normstruktur (Tatbestand → Rechtsfolge), Verweise (§, Abs., S.), Legaldefinitionen, „soweit“, „sofern“, „unbeschadet“.',
    examples: ['Soweit nichts anderes vereinbart ist, …', 'Unbeschadet des § 5 …'],
  },
  {
    id: 'term-kuendigung-ruecktritt',
    label: 'Kündigung ≠ Rücktritt',
    level: 'C1',
    category: 'terminology',
    explanation: 'Kündigung beendet ein Dauerschuldverhältnis für die Zukunft (PL: wypowiedzenie). Rücktritt wirkt auf den Vertrag insgesamt zurück (PL: odstąpienie od umowy).',
    pl: 'wypowiedzenie ≠ odstąpienie od umowy.',
    examples: ['Der Spieler kann den Vertrag mit einer Frist von … kündigen.'],
  },
  {
    id: 'term-vertragsstrafe',
    label: 'Vertragsstrafe (kara umowna)',
    level: 'C1',
    category: 'terminology',
    explanation: 'PL „kara umowna“ = DE „Vertragsstrafe“ (§§ 339 ff. BGB). Nicht: „Vertragsbuße“, nicht bloß „Strafe“.',
    examples: ['Für den Fall der Zuwiderhandlung wird eine Vertragsstrafe in Höhe von … fällig.'],
  },
  {
    id: 'uebersetzung-zahlen',
    label: 'Zahlen, Daten & Beträge exakt übertragen',
    level: 'B2',
    category: 'translation',
    explanation: 'Beträge, Daten, Fristen werden vollständig und exakt übertragen – deutsches Format: 1.500.000,00 EUR, 30.06.2027.',
    pl: 'Niemiecki zapis liczb: kropka dla tysięcy, przecinek dla części dziesiętnych.',
    examples: ['1,5 mln euro → 1.500.000 EUR'],
  },
  {
    id: 'uebersetzung-aequivalenz',
    label: 'Funktionale Äquivalenz (Recht)',
    level: 'C2',
    category: 'translation',
    explanation: 'Rechtsbegriffe sind an ein Rechtssystem gebunden. Erst Begriff → Bedeutung → Entsprechung im Zielsystem → Übersetzungsentscheidung (ggf. mit Erläuterung).',
    examples: ['Geschäftsführer (GmbH) ≈ członek zarządu spółki z o.o. – nicht „dyrektor“.'],
  },
];

export const TARGET_BY_ID: Record<string, LanguageTarget> = Object.fromEntries(TARGETS.map((t) => [t.id, t]));
