import { openDb } from "../src/data/db";
import { buildDataset } from "../src/data/facts";
import { todayView } from "../src/coach/today";
import { generateInsights } from "../src/coach/insights";
import { buildPlan } from "../src/coach/planner";
import { howIWorkBest, weeklyReview, biggestLever, knowledgeState } from "../src/coach/weekly";
import { buildReport } from "../src/reports/build";
const db = openDb(process.argv[2] ?? "data/apex.db");
let t = Date.now();
const ds = buildDataset(db);
console.log("dataset", Date.now() - t, "ms", ds.days.length, "days", ds.sessions.length, "sessions"); t = Date.now();
const ins = generateInsights(ds);
console.log("insights", Date.now() - t, "ms", ins.length); t = Date.now();
const tv = todayView(ds, ins);
console.log("today", Date.now() - t, "ms"); t = Date.now();
console.log(JSON.stringify({ german: tv.german, phone: tv.phone.total, exec: tv.execution, streak: tv.streak, pace: tv.goalPace, bottleneck: tv.bottleneck?.title, weak: tv.topWeakness?.title, mia: tv.mostImportantAction?.action, prio: tv.priorities, sus: tv.sustainability, mom: tv.momentum }, null, 1));
for (const i of ins) console.log(i.priority, i.kind, i.title, "|", i.facts[0]);
const plan = buildPlan(ds); console.log("plan", plan.totalMinutes, plan.realism.label, plan.blocks.map(b=>`${b.start} ${b.label} ${b.minutes}`));
console.log(JSON.stringify(weeklyReview(ds, ins), null, 1));
console.log(biggestLever(ds, ins));
const ks = knowledgeState(ds, ins); console.log(ks.known.slice(0,4), ks.likely.slice(0,4));
console.log(JSON.stringify(howIWorkBest(ds), null, 1).slice(0, 3000));
t = Date.now(); buildReport(ds, "quarter", ds.asOf, ins); console.log("report", Date.now() - t, "ms");
