import { chromium } from '@playwright/test';
const out = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:4174');
await p.waitForTimeout(600);
const G = (fn, arg) => p.evaluate(fn, arg);
await G(() => { const g = window.__game; g.getState().newGame({ first: 'Grzegorz', last: 'Nowak', anrede: 'Herr' }); g.getState().setScreen('world'); g.setState({ location: 'kreuzberg', time: '08:12', flags: { intro_done: true, kb_arrived: true }, rel: { kasia: 42, pohl: 5 } }); g.getState().applyEffects([{ type: 'startMission', mission: 'm_key' }], 'x'); });
await p.waitForTimeout(1500);
await G(() => window.__game.getState().startDialogue('key_main'));
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}/i1-npc-line.png` });
await p.click('[data-testid=continue]');
await p.waitForTimeout(800);
await p.fill('[data-testid=answer]', 'Guten Morgen Frau Wiesner! Ich bin Grzegorz, ich komme aus Polen und ich habe heute in Berlin angekommen. Ich arbeite in eine Kanzlei.');
await p.screenshot({ path: `${out}/i2-input.png` });
await p.click('[data-testid=submit]');
await p.waitForTimeout(900);
await p.click('text=Details');
await p.waitForTimeout(400);
await p.screenshot({ path: `${out}/i3-eval.png` });
// inspection
await G(() => { const g = window.__game; g.getState().endDialogue(); g.setState({ location: 'kanzlei', time: '14:50', flags: { ...g.getState().flags, k_arrived: true, briefed: true } }); g.getState().applyEffects([{ type: 'startMission', mission: 'm_contract' }], 'y'); });
await p.waitForTimeout(1200);
await G(() => window.__game.getState().startDialogue('k_desk'));
await p.waitForTimeout(900);
await p.click('[data-line=pl7]'); await p.click('[data-line=pl10]');
await p.screenshot({ path: `${out}/i4-inspect.png` });
await p.click('[data-testid=inspect-submit]');
await p.waitForTimeout(500);
await p.screenshot({ path: `${out}/i5-inspect-result.png` });
// compose
await G(() => { const g = window.__game; g.getState().endDialogue(); g.setState({ flags: { ...g.getState().flags, compared: true, translated: true } }); });
await p.waitForTimeout(600);
await G(() => window.__game.getState().startDialogue('k_desk'));
await p.waitForTimeout(700);
await p.click('[data-testid=continue]');
await p.waitForTimeout(700);
await p.screenshot({ path: `${out}/i6-compose.png` });
// call
await G(() => { const g = window.__game; g.getState().endDialogue(); g.getState().startDialogue('call_kessler'); });
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}/i7-call.png` });
await G(() => { const g = window.__game; g.getState().endDialogue(); g.getState().openOverlay('phone', null); });
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/i8-phone.png` });
await G(() => window.__game.getState().openOverlay('profile'));
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/i9-dossier.png` });
await G(() => window.__game.getState().openOverlay('map'));
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}/i10-map.png` });
await G(() => { const g = window.__game; g.getState().closeOverlay(); g.getState().applyEffects([{ type: 'completeMission', mission: 'm_key', outcome: 'Schlüssel übernommen' }], 'z'); g.getState().openOverlay('debrief'); });
await p.waitForTimeout(1800);
await p.screenshot({ path: `${out}/i11-debrief.png` });
await G(() => { const g = window.__game; g.getState().shiftDebrief(); g.getState().openOverlay('training'); });
await p.waitForTimeout(600);
await p.screenshot({ path: `${out}/i12-training.png` });
await b.close();
