import { dlg } from '../../dsl';

/** MISSION: DAS AMT — Bürgeramt, Tag 2 */

export const amt_display = dlg('amt_display', [
  {
    id: 'x1',
    skill: 'reading',
    document: {
      kind: 'board',
      title: 'AUFRUF',
      lines: [
        { text: 'B-214   →   Platz 2', mono: true },
        { text: 'B-215   →   Platz 7', mono: true },
        { text: 'B-217   →   Platz 4', mono: true, highlight: true },
        { text: 'Bitte halten Sie Ihre Unterlagen bereit. Unvollständige Anträge können nicht bearbeitet werden.', small: true },
      ],
    },
    next: 'x2',
  },
  { id: 'x2', speaker: 'narrator', direction: 'B-217 – das sind Sie. Platz 4.', end: true },
]);

export const amt_main = dlg('amt_main', [
  { id: 'a0', branch: [{ condition: { flag: 'amt_registered' }, next: 'a_done' }, { condition: { flag: 'amt_retry' }, next: 'a6' }], next: 'a1' },
  { id: 'a_done', speaker: 'amt', text: 'Sie sind angemeldet. Schönen Tag noch.', gloss: 'Jest Pan/Pani zameldowany/a. Miłego dnia.', end: true },
  {
    id: 'a1',
    speaker: 'amt',
    direction: 'Herr Schulze. Strickjacke, Lesebrille, zwei Monitore. Auf dem Tisch ein Schild: „Bitte nicht klopfen.“',
    text: 'Guten Morgen. B-217? Nehmen Sie bitte Platz. Was kann ich für Sie tun?',
    gloss: 'Dzień dobry. B-217? Proszę usiąść. W czym mogę pomóc?',
    effects: [{ type: 'objective', mission: 'm_amt', objective: 'go' }],
    next: 'a2',
  },
  {
    id: 'a2',
    speaker: 'player',
    input: {
      task: 'Erklären Sie, dass Sie Ihren Wohnsitz anmelden möchten.',
      taskGloss: 'Wyjaśnij, że chcesz zameldować miejsce zamieszkania.',
      mode: 'speak',
      skill: 'speaking',
      register: 'formal',
      targets: ['hoeflichkeit-k2', 'perfekt-sein', 'verb-praep'],
      required: [{ id: 'reg', label: 'Anmeldung des Wohnsitzes', patterns: ['anmeld', 'wohnsitz', 'meldebescheinigung', 'ummeld', 'eingezogen', 'umgezogen', 'melden'] }],
      bonuses: [
        { pattern: String.raw`moechte|wuerde gern|haette gern`, dimension: 'naturalness', note: 'Höflich formuliert', weight: 15 },
        { pattern: String.raw`(meinen )?wohnsitz anmelden`, dimension: 'idiomaticity', note: '„den Wohnsitz anmelden“ – exakte Behördensprache', weight: 25 },
        { pattern: String.raw`bin [^.]*(eingezogen|gezogen)`, dimension: 'naturalness', note: 'Kontext gegeben (eingezogen)', weight: 12 },
        { pattern: String.raw`graefestr`, dimension: 'precision', note: 'Adresse genannt', weight: 8 },
      ],
      models: ['Guten Morgen. Ich möchte meinen Wohnsitz anmelden. Ich bin vor zwei Tagen in die Graefestraße 12 eingezogen.'],
      vocab: ['anmelden', 'wohnsitz'],
      onSuccess: 'a3',
      onPartial: 'a3',
      onFail: 'a2f',
    },
  },
  { id: 'a2f', speaker: 'amt', text: 'Ah, eine Anmeldung, nehme ich an? Wegen des Umzugs?', gloss: 'Zakładam, że chodzi o zameldowanie? W związku z przeprowadzką?', next: 'a2f_c' },
  {
    id: 'a2f_c',
    speaker: 'player',
    choices: [
      { text: 'Ja, genau. Ich möchte mich anmelden.', quality: 'natural', next: 'a3' },
      { text: 'Ja. Anmeldung.', quality: 'correct', next: 'a3' },
    ],
  },
  {
    id: 'a3',
    speaker: 'amt',
    listening: true,
    skill: 'listening',
    text: 'Gut. Dann brauche ich Ihren Personalausweis oder Reisepass, das ausgefüllte Anmeldeformular und die Wohnungsgeberbestätigung.',
    gloss: 'Dobrze. Potrzebuję dowodu osobistego lub paszportu, wypełnionego formularza meldunkowego i zaświadczenia od wynajmującego.',
    next: 'a4',
  },
  { id: 'a4', branch: [{ condition: { item: 'wgb' }, next: 'a5ok' }], next: 'a5no' },
  {
    id: 'a5ok',
    speaker: 'player',
    choices: [{ text: 'Hier, bitte: mein Reisepass, das Formular und die Wohnungsgeberbestätigung.', quality: 'natural', next: 'a6' }],
  },
  {
    id: 'a5no',
    speaker: 'narrator',
    direction: 'Die Wohnungsgeberbestätigung. Sie haben sie nicht. Kasias SMS von gestern: „Frag sie nach der Wohnungsgeberbestätigung …“',
    next: 'a5no_c',
  },
  {
    id: 'a5no_c',
    speaker: 'player',
    choices: [
      { text: 'Die Wohnungsgeberbestätigung habe ich leider noch nicht. Könnte ich sie nachreichen?', quality: 'natural', targets: ['hoeflichkeit-k2'], next: 'a5no2' },
      { text: 'Ich habe das nicht. Können Sie das trotzdem machen?', quality: 'correct', next: 'a5no2' },
    ],
  },
  {
    id: 'a5no2',
    speaker: 'amt',
    listening: true,
    skill: 'listening',
    text: 'Nachreichen geht leider nicht. Ohne Wohnungsgeberbestätigung kann die Anmeldung nicht durchgeführt werden. Wenn Sie sie heute noch bekommen, kann ich Sie um zehn Uhr vierzig dazwischenschieben.',
    gloss: 'Niestety nie można dosłać. Bez zaświadczenia od wynajmującego nie można przeprowadzić zameldowania. Jeśli dostanie je Pan/Pani dziś, mogę wcisnąć Pana/Panią o 10:40.',
    effects: [{ type: 'flag', flag: 'amt_blocked' }, { type: 'memory', npc: 'amt', text: 'Kam ohne Wohnungsgeberbestätigung.' }],
    next: 'a5mail',
  },
  {
    id: 'a5mail',
    speaker: 'player',
    direction: 'Vor dem Bürgeramt. Sie schreiben Frau Wiesner eine E-Mail.',
    compose: { to: 'e.wiesner@hausverwaltung-wiesner.de', subject: 'Wohnungsgeberbestätigung – Graefestraße 12, 3. OG links' },
    input: {
      task: 'Bitten Sie Frau Wiesner höflich um die Wohnungsgeberbestätigung und erklären Sie, warum Sie sie heute brauchen.',
      taskGloss: 'Poproś uprzejmie o zaświadczenie i wyjaśnij, dlaczego potrzebujesz go dziś.',
      mode: 'write',
      skill: 'writing',
      register: 'formal',
      minWords: 20,
      targets: ['hoeflichkeit-k2', 'email-register', 'nebensatz-verbend', 'infinitiv-zu'],
      required: [
        { id: 'ask', label: 'eine höfliche Bitte', patterns: ['bitte', 'koennten sie', 'waere es moeglich', 'wuerden sie', 'moechte sie bitten'] },
        { id: 'doc', label: 'die Wohnungsgeberbestätigung', patterns: ['wohnungsgeberbestaetigung', 'bestaetigung'] },
        { id: 'why', label: 'der Grund (Anmeldung, heute)', patterns: ['anmeld', 'buergeramt', 'amt', 'meldebehoerde', 'termin'] },
      ],
      bonuses: [
        { pattern: String.raw`sehr geehrte frau wiesner`, dimension: 'register', note: 'Formelle Anrede', weight: 12 },
        { pattern: String.raw`mit freundlichen gruessen`, dimension: 'style', note: 'Formelle Grußformel', weight: 10 },
        { pattern: String.raw`waere es moeglich|koennten sie mir`, dimension: 'naturalness', note: 'Höfliche Bitte im Konjunktiv II', weight: 15 },
        { pattern: String.raw`vielen dank im voraus|fuer ihre (hilfe|unterstuetzung)|entschuldigen sie die (kurzfristige|eilige)`, dimension: 'idiomaticity', note: 'Feste Wendung der Korrespondenz', weight: 15 },
        { pattern: String.raw`per e-?mail|als pdf|eingescannt|scan`, dimension: 'precision', note: 'Praktischer Übermittlungsweg vorgeschlagen', weight: 10 },
      ],
      models: [
        'Sehr geehrte Frau Wiesner,\n\nich habe heute meinen Termin im Bürgeramt, und leider fehlt mir für die Anmeldung noch die Wohnungsgeberbestätigung. Wäre es möglich, sie mir heute noch als PDF per E-Mail zu schicken? Ich habe um 10:40 Uhr einen Ersatztermin.\n\nVielen Dank im Voraus und entschuldigen Sie die kurzfristige Bitte.\n\nMit freundlichen Grüßen\n{first} {last}',
      ],
      vocab: ['wohnungsgeberbestaetigung', 'anmelden'],
      onSuccess: 'a5ok_mail',
      onPartial: 'a5ok_mail',
      onFail: 'a5bad_mail',
    },
  },
  {
    id: 'a5ok_mail',
    speaker: 'wiesner',
    audio: false,
    text: 'Guten Tag {first} {last}, anbei die Wohnungsgeberbestätigung. Sie hätten auch gestern fragen können. Mit freundlichen Grüßen, E. Wiesner',
    gloss: 'W załączniku zaświadczenie. Mógł Pan / mogła Pani zapytać wczoraj.',
    effects: [{ type: 'item', item: 'wgb' }, { type: 'flag', flag: 'amt_retry' }, { type: 'time', set: '10:40' }],
    next: 'a5back',
  },
  {
    id: 'a5bad_mail',
    speaker: 'wiesner',
    audio: false,
    text: 'Ich verstehe Ihre E-Mail nicht ganz. Meinen Sie die Wohnungsgeberbestätigung? Anbei. E. Wiesner',
    gloss: 'Nie do końca rozumiem maila. Chodzi o zaświadczenie od wynajmującego? W załączniku.',
    effects: [{ type: 'item', item: 'wgb' }, { type: 'flag', flag: 'amt_retry' }, { type: 'rel', npc: 'wiesner', delta: -2 }, { type: 'time', set: '10:40' }],
    next: 'a5back',
  },
  { id: 'a5back', speaker: 'narrator', direction: '10:40. Wieder Platz 4. Herr Schulze nickt, als hätte er es gewusst.', next: 'a6' },
  {
    id: 'a6',
    speaker: 'amt',
    listening: true,
    skill: 'listening',
    text: 'Danke. Eine Frage noch für das Melderegister: Gehören Sie einer Religionsgemeinschaft an, die Kirchensteuer erhebt? Das wird an das Finanzamt übermittelt.',
    gloss: 'Dziękuję. Jeszcze pytanie do rejestru: czy należy Pan/Pani do wspólnoty religijnej pobierającej podatek kościelny? Informacja trafia do urzędu skarbowego.',
    next: 'a6c',
  },
  {
    id: 'a6c',
    speaker: 'player',
    choices: [
      { text: 'Nein, ich gehöre keiner Religionsgemeinschaft an.', quality: 'professional', targets: ['dativ-praep'], next: 'a7', effects: [{ type: 'flag', flag: 'church_none' }] },
      { text: 'Ja, ich bin römisch-katholisch.', quality: 'natural', next: 'a7', effects: [{ type: 'flag', flag: 'church_rk' }] },
      { text: 'Was bedeutet Kirchensteuer genau?', quality: 'correct', next: 'a6explain' },
    ],
  },
  {
    id: 'a6explain',
    speaker: 'amt',
    text: 'Wenn Sie Mitglied einer Kirche sind, die Kirchensteuer erhebt, zahlen Sie in Berlin neun Prozent Ihrer Lohnsteuer zusätzlich. Das wird automatisch vom Gehalt abgezogen.',
    gloss: 'Jeśli jest Pan/Pani członkiem Kościoła pobierającego podatek kościelny, płaci Pan/Pani w Berlinie dodatkowo 9% podatku od wynagrodzenia. Potrącane automatycznie.',
    effects: [{ type: 'vocab', words: ['kirchensteuer', 'lohnsteuer'], mode: 'seen' }],
    next: 'a6c2',
  },
  {
    id: 'a6c2',
    speaker: 'player',
    choices: [
      { text: 'Verstehe, danke. Dann: nein, ich gehöre keiner Religionsgemeinschaft an.', quality: 'professional', next: 'a7', effects: [{ type: 'flag', flag: 'church_none' }] },
      { text: 'Verstehe. Ich bin römisch-katholisch.', quality: 'natural', next: 'a7', effects: [{ type: 'flag', flag: 'church_rk' }] },
    ],
  },
  {
    id: 'a7',
    speaker: 'amt',
    listening: true,
    skill: 'listening',
    text: 'Gut. Ihre Meldebescheinigung wird gerade ausgedruckt. Ihre steuerliche Identifikationsnummer wird Ihnen in den nächsten zwei bis vier Wochen per Post zugeschickt – nicht per E-Mail.',
    gloss: 'Dobrze. Zaświadczenie o zameldowaniu właśnie się drukuje. Numer identyfikacji podatkowej zostanie przesłany pocztą w ciągu 2–4 tygodni – nie mailem.',
    next: 'a8',
  },
  {
    id: 'a8',
    speaker: 'player',
    direction: 'Was hat er gesagt – wie und wann bekommen Sie die Steuer-ID?',
    choices: [
      { text: 'Per Post, in zwei bis vier Wochen.', quality: 'natural', targets: ['passiv'], next: 'a9', effects: [{ type: 'skill', skill: 'listening', delta: 3 }] },
      { text: 'Sofort, zusammen mit der Meldebescheinigung.', quality: 'incorrect', targets: ['passiv'], feedback: '„wird … zugeschickt“ = Passiv: Sie bekommt man per Post, in 2–4 Wochen.', next: 'a8wrong', effects: [{ type: 'skill', skill: 'listening', delta: -3 }] },
      { text: 'Per E-Mail, morgen.', quality: 'incorrect', targets: ['passiv'], feedback: 'Er hat ausdrücklich gesagt: „nicht per E-Mail“.', next: 'a8wrong', effects: [{ type: 'skill', skill: 'listening', delta: -3 }] },
    ],
  },
  { id: 'a8wrong', speaker: 'amt', text: 'Per Post. In zwei bis vier Wochen. Achten Sie auf Ihren Briefkasten.', gloss: 'Pocztą. Za 2–4 tygodnie. Proszę pilnować skrzynki.', next: 'a9' },
  {
    id: 'a9',
    speaker: 'amt',
    text: 'Hier ist Ihre Meldebescheinigung. Willkommen in Berlin.',
    gloss: 'Oto zaświadczenie o zameldowaniu. Witamy w Berlinie.',
    direction: 'Zum ersten Mal: ein Lächeln.',
    effects: [
      { type: 'item', item: 'meldebescheinigung' },
      { type: 'flag', flag: 'amt_registered' },
      { type: 'objective', mission: 'm_amt', objective: 'register' },
      { type: 'completeMission', mission: 'm_amt', outcome: 'Offiziell Berlinerin/Berliner' },
      { type: 'message', from: 'lukas', text: '11 Uhr, Büro. Bring Kaffee mit. Viel Kaffee. ☕☕☕ Der Artikel ist online.' },
      { type: 'chapterCard', title: 'FORTSETZUNG FOLGT', subtitle: '48 STUNDEN · in Produktion' },
    ],
    end: true,
  },
]);
