import { dlg } from '../../dsl';

/** MISSION: ERSTER KAFFEE + MISSION: DER ANRUF */

export const cafe_order = dlg('cafe_order', [
  {
    id: 'c1',
    speaker: 'emre',
    direction: 'Die Siebträgermaschine faucht. Hinter der Theke: ein Mann mit Bart, Geschirrtuch über der Schulter.',
    text: 'Morgen! Was darf’s sein?',
    gloss: 'Dzień dobry! Co podać?',
    effects: [{ type: 'objective', mission: 'm_cafe', objective: 'enter' }],
    next: 'c2',
  },
  {
    id: 'c2',
    speaker: 'player',
    input: {
      task: 'Bestellen Sie einen Kaffee und etwas zu essen.',
      taskGloss: 'Zamów kawę i coś do jedzenia.',
      placeholder: 'Ich hätte gern …',
      mode: 'speak',
      skill: 'speaking',
      register: 'any',
      targets: ['hoeflichkeit-k2', 'adj-endungen'],
      required: [
        { id: 'drink', label: 'ein Getränk', patterns: ['kaffee', 'cappuccino', 'latte', 'espresso', 'flat white', 'milchkaffee', 'tee', 'americano', 'kakao', 'cortado', 'chai'] },
        { id: 'food', label: 'etwas zu essen', patterns: ['croissant', 'brot', 'broetchen', 'schrippe', 'kuchen', 'sandwich', 'bagel', 'franzbroetchen', 'muesli', 'stulle', 'toast', 'simit', 'boerek', 'etwas zu essen', 'muffin', 'brezel', 'omelett', 'porridge'] },
      ],
      errors: [
        {
          pattern: String.raw`kann ich (einen|ein|eine)[^.?!]* haben`,
          target: 'hoeflichkeit-k2',
          category: 'idioms',
          severity: 1,
          message: '„Kann ich … haben?“ ist aus dem Englischen („Can I have …“) übersetzt. Natürlich: „Ich hätte gern …“, „Ich nehme …“ oder einfach „Einen Cappuccino, bitte.“',
        },
        { pattern: String.raw`\bich will\b`, target: 'hoeflichkeit-k2', category: 'register', severity: 1, message: '„Ich will …“ klingt an der Theke fordernd. Besser: „Ich hätte gern …“ / „Ich nehme …“' },
        {
          pattern: String.raw`einen (grosse|grosses|grosser|kleine|kleines|kleiner|schwarze|schwarzes|schwarzer|doppelte|doppelter) (kaffee|cappuccino|tee|espresso|milchkaffee|latte)`,
          target: 'adj-endungen',
          category: 'adjectiveEndings',
          severity: 2,
          message: 'Akkusativ maskulin nach „einen“: -en → „einen großen Kaffee“.',
          pl: 'Biernik rodzaju męskiego: einen großen Kaffee.',
        },
      ],
      bonuses: [
        { pattern: String.raw`haette gerne?|ich nehme|fuer mich`, dimension: 'naturalness', note: '„Ich hätte gern / Ich nehme“ – so bestellt man', weight: 22 },
        { pattern: String.raw`\bbitte\b`, dimension: 'register', note: '„bitte“', weight: 8 },
        { pattern: String.raw`einen (grossen|kleinen|schwarzen|doppelten)`, dimension: 'idiomaticity', note: 'Adjektivendung sauber (einen großen …)', weight: 18 },
        { pattern: 'hafermilch|mit milch|ohne zucker', dimension: 'idiomaticity', note: 'Berlin-tauglich präzisiert', weight: 10 },
      ],
      models: ['Ich hätte gern einen großen Cappuccino mit Hafermilch und ein Franzbrötchen, bitte.', 'Einen Milchkaffee und ein Croissant, bitte.'],
      vocab: ['bestellen'],
      onSuccess: 'c3s',
      onPartial: 'c3p',
      onFail: 'c3f',
    },
  },
  { id: 'c3s', speaker: 'emre', text: 'Kommt sofort. Für hier oder zum Mitnehmen?', gloss: 'Już się robi. Na miejscu czy na wynos?', effects: [{ type: 'objective', mission: 'm_cafe', objective: 'order' }], next: 'c3c' },
  { id: 'c3p', speaker: 'emre', text: 'Alles klar – ich glaub, ich weiß, was du meinst. Für hier oder zum Mitnehmen?', gloss: 'Jasne – chyba wiem, o co chodzi. Na miejscu czy na wynos?', effects: [{ type: 'objective', mission: 'm_cafe', objective: 'order' }], next: 'c3c' },
  { id: 'c3f', speaker: 'emre', text: 'Sorry? … Kaffee? Okay, Kaffee. Und was zu essen? Ein Croissant vielleicht?', gloss: 'Słucham? … Kawa? OK. A coś do jedzenia? Może croissant?', next: 'c3f_c' },
  {
    id: 'c3f_c',
    speaker: 'player',
    choices: [
      { text: 'Ja, gern. Ein Croissant, bitte.', quality: 'natural', next: 'c3c', effects: [{ type: 'objective', mission: 'm_cafe', objective: 'order' }] },
      { text: 'Ja. Croissant.', quality: 'correct', next: 'c3c', effects: [{ type: 'objective', mission: 'm_cafe', objective: 'order' }] },
    ],
  },
  {
    id: 'c3c',
    speaker: 'player',
    choices: [
      { text: 'Für hier, bitte.', quality: 'natural', next: 'c4' },
      { text: 'Zum Mitnehmen.', quality: 'natural', next: 'c4', effects: [{ type: 'flag', flag: 'coffee_to_go' }] },
    ],
  },
  {
    id: 'c4',
    speaker: 'emre',
    listening: true,
    skill: 'listening',
    text: 'Macht sieben achtzig. Aber sorry, das Kartenlesegerät spinnt heute. Nur bar.',
    gloss: 'Razem 7,80. Ale sorry, terminal dziś wariuje. Tylko gotówka.',
    next: 'c4c',
  },
  {
    id: 'c4c',
    speaker: 'player',
    direction: 'Sie haben kein Bargeld. Nicht einen Cent.',
    choices: [
      { text: 'Oh nein, ich habe kein Bargeld dabei. Gibt es hier in der Nähe einen Geldautomaten?', quality: 'natural', targets: ['adj-endungen'], next: 'c5atm' },
      { text: 'Kann ich vielleicht mit dem Handy bezahlen? Per PayPal?', quality: 'correct', next: 'c5pp' },
      { text: 'Ich habe nur Karte. Was mache ich jetzt?', quality: 'correct', next: 'c5atm' },
    ],
  },
  {
    id: 'c5atm',
    speaker: 'emre',
    text: 'Gegenüber, neben dem Späti. Aber weißt du was? Du bist neu hier, oder? Zahl einfach morgen. Ich vertrau dir.',
    gloss: 'Naprzeciwko, obok Späti. Ale wiesz co? Jesteś tu nowy/nowa, co? Zapłać jutro. Ufam ci.',
    effects: [{ type: 'rel', npc: 'emre', delta: 8 }, { type: 'flag', flag: 'emre_credit' }, { type: 'memory', npc: 'emre', text: 'Schuldet Emre noch 7,80 €.' }],
    next: 'c6',
  },
  {
    id: 'c5pp',
    speaker: 'emre',
    text: 'Klar, geht auch. Da hängt der QR-Code. … Perfekt, ist angekommen.',
    gloss: 'Jasne, też można. Tam wisi kod QR. … Super, doszło.',
    effects: [{ type: 'rel', npc: 'emre', delta: 2 }],
    next: 'c6',
  },
  {
    id: 'c6',
    speaker: 'emre',
    text: 'Und, was machst du in Berlin? Du siehst aus, als wärst du seit fünf Uhr wach.',
    gloss: 'A co robisz w Berlinie? Wyglądasz, jakbyś nie spał/a od piątej.',
    next: 'c7',
  },
  {
    id: 'c7',
    speaker: 'player',
    input: {
      task: 'Erzählen Sie Emre kurz, dass Sie heute angekommen sind und was Sie in Berlin machen. Er duzt Sie – Sie dürfen auch duzen.',
      taskGloss: 'Powiedz krótko, że przyjechałeś/aś dziś i co będziesz robić w Berlinie. Emre mówi na „ty”.',
      mode: 'speak',
      skill: 'speaking',
      register: 'informal',
      targets: ['perfekt-sein', 'v2-inversion', 'du-sie'],
      required: [
        { id: 'arrival', label: 'dass Sie gerade angekommen sind', patterns: ['angekommen', 'gekommen', 'heute morgen', 'seit heute', 'neu', 'gerade erst', 'erst heute', 'hergezogen', 'umgezogen'] },
        { id: 'purpose', label: 'was Sie in Berlin machen', patterns: ['arbeit', 'job', 'kanzlei', 'jurist', 'anwalt', 'uebersetz', 'studier', 'stelle', 'anfang', 'fange', 'firma'] },
      ],
      bonuses: [
        { pattern: String.raw`bin [^.]*angekommen`, dimension: 'idiomaticity', note: 'Perfekt mit „sein“ – sauber', weight: 20 },
        { pattern: String.raw`stimmt|genau|haha|echt|ehrlich gesagt|ziemlich`, dimension: 'naturalness', note: 'Natürlicher Gesprächston', weight: 15 },
        { pattern: String.raw`seit (vier|fuenf|drei|halb)|seit gestern|die ganze nacht`, dimension: 'naturalness', note: 'Auf Emres Bemerkung eingegangen', weight: 12 },
        { pattern: String.raw`fange [^.]*\ban\b|ab montag`, dimension: 'idiomaticity', note: 'Trennbares Verb korrekt', weight: 10 },
      ],
      models: ['Stimmt, ich bin heute Morgen aus Warschau angekommen. Ab Montag arbeite ich in einer Kanzlei in Mitte.', 'Ja, seit vier Uhr! Ich bin gerade erst angekommen – ich fange nächste Woche in einer Kanzlei an.'],
      onSuccess: 'c8s',
      onPartial: 'c8p',
      onFail: 'c8f',
    },
  },
  {
    id: 'c8s',
    speaker: 'emre',
    text: 'Kanzlei, krass. Dann bist du ja bald reich und zahlst meine Miete. Willkommen im Kiez!',
    gloss: 'Kancelaria, no nieźle. To niedługo będziesz bogaty/a i zapłacisz mój czynsz. Witaj w dzielnicy!',
    effects: [{ type: 'rel', npc: 'emre', delta: 5 }, { type: 'memory', npc: 'emre', text: 'Arbeitet in einer Kanzlei in Mitte.' }],
    next: 'c9',
  },
  { id: 'c8p', speaker: 'emre', text: 'Ah, okay, verstehe. Arbeit, Kanzlei – cool. Willkommen!', gloss: 'Aha, rozumiem. Praca, kancelaria – super. Witaj!', next: 'c9' },
  { id: 'c8f', speaker: 'emre', text: 'Hm? Ach, egal – Hauptsache, du bist da. Willkommen!', gloss: 'Hm? A, nieważne – najważniejsze, że jesteś. Witaj!', next: 'c9' },
  {
    id: 'c9',
    speaker: 'narrator',
    direction: 'Der Cappuccino ist perfekt. Sie sitzen am Fenster. Draußen fährt ein Lastenrad vorbei, beladen mit zwei Kindern und einem Kürbis. Dann: Ihr Telefon. Unbekannte Nummer, +49 30 …',
    effects: [
      { type: 'flag', flag: 'cafe_ordered' },
      { type: 'completeMission', mission: 'm_cafe', outcome: 'Frühstück im Kiez' },
      { type: 'time', set: '10:52' },
      { type: 'startMission', mission: 'm_call' },
      { type: 'call', dialogue: 'call_kessler', from: 'kessler', delayMs: 2500 },
    ],
    end: true,
  },
]);

export const cafe_emre = dlg('cafe_emre', [
  {
    id: 'e0',
    branch: [
      { condition: { all: [{ mission: 'm_cafe', status: 'active' }, { flag: 'cafe_ordered', is: false }] }, next: '@cafe_order' },
      { condition: { flag: 'emre_credit' }, next: 'e1credit' },
    ],
    next: 'e1',
  },
  {
    id: 'e1',
    speaker: 'emre',
    text: 'Na, wieder da? Die Maschine ist warm.',
    gloss: 'No, znowu jesteś? Ekspres jest ciepły.',
    next: 'e2',
  },
  {
    id: 'e1credit',
    speaker: 'emre',
    text: 'Na, {first}! Und die sieben achtzig? Kleiner Scherz. Oder nicht.',
    gloss: 'No, {first}! A te 7,80? Żartuję. A może nie.',
    next: 'e1credit_c',
  },
  {
    id: 'e1credit_c',
    speaker: 'player',
    choices: [
      { text: 'Hier, bitte – und danke noch mal, dass du mir vertraut hast.', quality: 'natural', targets: ['perfekt-sein', 'du-sie'], next: 'e2', effects: [{ type: 'flag', flag: 'emre_credit', value: false }, { type: 'rel', npc: 'emre', delta: 4 }] },
      { text: 'Morgen, versprochen!', quality: 'correct', next: 'e2' },
    ],
  },
  { id: 'e2', retrieval: { channel: 'dialogue', speaker: 'emre' }, next: 'e3' },
  { id: 'e3', speaker: 'emre', text: 'Bis später! Und grüß Kasia, falls du sie siehst.', gloss: 'Na razie! I pozdrów Kasię.', end: true },
]);

export const cafe_window = dlg('cafe_window', [
  {
    id: 'w1',
    speaker: 'narrator',
    direction: 'Am Nebentisch streiten zwei Studentinnen über eine WG-Besichtigung: „Die wollten achthundert warm – für neun Quadratmeter!“ Berlin, in einem Satz.',
    effects: [{ type: 'skill', skill: 'listening', delta: 0.5 }],
    end: true,
  },
]);

export const call_kessler = dlg(
  'call_kessler',
  [
    {
      id: 'ca1',
      speaker: 'kessler',
      listening: true,
      skill: 'listening',
      text: 'Kessler, Kanzlei Kessler und Aydın, guten Morgen. Spreche ich mit {anrede}?',
      gloss: 'Kessler, kancelaria Kessler i Aydın, dzień dobry. Czy rozmawiam z {anrede}?',
      effects: [{ type: 'objective', mission: 'm_call', objective: 'answer' }],
      next: 'ca1c',
    },
    {
      id: 'ca1c',
      speaker: 'player',
      choices: [
        { text: 'Ja, am Apparat. Guten Morgen, Frau Dr. Kessler.', quality: 'professional', targets: ['du-sie'], next: 'ca2', effects: [{ type: 'rel', npc: 'kessler', delta: 3 }] },
        { text: 'Ja, das bin ich.', quality: 'correct', next: 'ca2' },
        { text: 'Wer ist da, bitte?', quality: 'understandable', feedback: 'Sie hat sich bereits vorgestellt: Dr. Kessler von der Kanzlei.', next: 'ca1b', effects: [{ type: 'skill', skill: 'listening', delta: -2 }] },
      ],
    },
    {
      id: 'ca1b',
      speaker: 'kessler',
      listening: true,
      text: 'Kessler. Jana Kessler, von der Kanzlei. Wir hatten das Vorstellungsgespräch per Video.',
      gloss: 'Kessler. Jana Kessler, z kancelarii. Mieliśmy rozmowę kwalifikacyjną przez wideo.',
      next: 'ca2',
    },
    {
      id: 'ca2',
      speaker: 'kessler',
      listening: true,
      skill: 'listening',
      text: 'Ich weiß, Sie fangen offiziell erst am Montag an. Aber wir haben ein Problem. Ein polnischer Spieler, unser Mandant, soll heute Abend beim FC Spree unterschreiben. Der Vertrag muss heute noch geprüft werden – und die polnische Übersetzung weicht offenbar von der deutschen Fassung ab.',
      gloss: 'Wiem, że oficjalnie zaczyna Pan/Pani w poniedziałek. Ale mamy problem. Polski piłkarz, nasz klient, ma dziś wieczorem podpisać kontrakt z FC Spree. Umowę trzeba sprawdzić jeszcze dziś – a polskie tłumaczenie najwyraźniej różni się od wersji niemieckiej.',
      next: 'ca3',
    },
    {
      id: 'ca3',
      speaker: 'kessler',
      listening: true,
      skill: 'listening',
      text: 'Könnten Sie um halb drei bei uns im Büro sein? Friedrichstraße 148, vierter Stock. Bringen Sie bitte Ihren Ausweis mit – für den Empfang.',
      gloss: 'Czy mógłby Pan / mogłaby Pani być u nas w biurze o 14:30? Friedrichstraße 148, czwarte piętro. Proszę zabrać dowód – do recepcji.',
      next: 'ca4',
    },
    {
      id: 'ca4',
      speaker: 'player',
      input: {
        task: 'Sagen Sie zu und bestätigen Sie Uhrzeit und Adresse.',
        taskGloss: 'Potwierdź, że przyjdziesz, oraz godzinę i adres.',
        mode: 'speak',
        skill: 'speaking',
        register: 'formal',
        targets: ['uhrzeit', 'hoeflichkeit-k2', 'trennbare-verben'],
        required: [
          { id: 'yes', label: 'Zusage', patterns: ['\\bja\\b', 'gern', 'natuerlich', 'selbstverstaendlich', 'in ordnung', 'kein problem', 'mache ich', 'komme', 'bin (dann )?da', 'werde da sein', 'passt', 'einverstanden', 'klar'] },
          { id: 'time', label: 'die Uhrzeit (halb drei = 14:30)', patterns: [String.raw`14[:.]? ?30`, 'halb drei', 'vierzehn uhr dreissig', '14 uhr 30', String.raw`2[:.]30`] },
          { id: 'place', label: 'die Adresse', patterns: ['friedrichstr', '148', 'hundertachtundvierzig', 'vierte[nr]? stock', String.raw`4\. (stock|og|etage)`] },
        ],
        errors: [
          {
            pattern: String.raw`15[:.]? ?30|halb vier|drei uhr dreissig|15 uhr|um drei\b|13[:.]30|3[:.]30`,
            target: 'uhrzeit',
            category: 'listening',
            severity: 3,
            message: '„halb drei“ = 14:30 – eine halbe Stunde VOR drei. Nicht 15:30.',
            pl: '„halb drei” = 14:30 (pół godziny przed trzecią).',
          },
          { pattern: String.raw`\b(24|184|184|418|841)\b`, category: 'listening', severity: 2, message: 'Die Hausnummer war 148 (hundertachtundvierzig).' },
        ],
        bonuses: [
          { pattern: 'selbstverstaendlich|sehr gern', dimension: 'register', note: 'Souveräne Zusage', weight: 12 },
          { pattern: String.raw`(ausweis|personalausweis|reisepass)`, dimension: 'precision', note: 'An den Ausweis gedacht', weight: 12 },
          { pattern: String.raw`bringe [^.]*(ausweis|reisepass)[^.]* mit`, dimension: 'idiomaticity', note: '„mitbringen“ korrekt getrennt', weight: 20 },
          { pattern: String.raw`(also|dann) (um )?(14[:.]? ?30|halb drei)`, dimension: 'naturalness', note: 'Zur Sicherheit zusammengefasst', weight: 12 },
          { pattern: String.raw`vierte[nr]? stock|4\. (stock|og)`, dimension: 'precision', note: 'Stockwerk bestätigt', weight: 8 },
        ],
        models: ['Selbstverständlich. Dann bin ich um 14:30 Uhr in der Friedrichstraße 148, vierter Stock – und bringe meinen Ausweis mit.'],
        vocab: ['mitbringen', 'ausweis'],
        onSuccess: 'ca5s',
        onPartial: 'ca5p',
        onFail: 'ca5f',
      },
    },
    { id: 'ca5s', speaker: 'kessler', text: 'Perfekt. Ich schicke Ihnen die Adresse noch per SMS. Bis gleich.', gloss: 'Świetnie. Wyślę jeszcze adres SMS-em. Do zobaczenia.', effects: [{ type: 'rel', npc: 'kessler', delta: 6 }], next: 'ca_end' },
    {
      id: 'ca5p',
      speaker: 'kessler',
      text: 'Also: halb drei – vierzehn Uhr dreißig –, Friedrichstraße 148. Ich schicke es Ihnen auch per SMS. Bis dann.',
      gloss: 'Czyli: 14:30, Friedrichstraße 148. Wyślę też SMS-em. Do zobaczenia.',
      effects: [{ type: 'rel', npc: 'kessler', delta: 1 }],
      next: 'ca_end',
    },
    {
      id: 'ca5f',
      speaker: 'kessler',
      rate: 0.85,
      text: 'Ich wiederhole: vierzehn Uhr dreißig. Friedrichstraße einhundertachtundvierzig. Haben Sie das?',
      gloss: 'Powtarzam: 14:30. Friedrichstraße 148. Zanotował Pan / zanotowała Pani?',
      next: 'ca5f_c',
    },
    {
      id: 'ca5f_c',
      speaker: 'player',
      choices: [
        { text: 'Ja: 14:30 Uhr, Friedrichstraße 148. Ich komme.', quality: 'correct', targets: ['uhrzeit'], next: 'ca_end' },
        { text: 'Ja: 15:30 Uhr.', quality: 'incorrect', targets: ['uhrzeit'], feedback: 'Vierzehn Uhr dreißig = 14:30 = halb drei.', next: 'ca5f2' },
      ],
    },
    { id: 'ca5f2', speaker: 'kessler', text: 'Nein – vierzehn Uhr dreißig. Halb drei. Ich schicke es Ihnen per SMS.', gloss: 'Nie – 14:30. Wpół do trzeciej. Wyślę SMS-em.', effects: [{ type: 'rel', npc: 'kessler', delta: -2 }], next: 'ca_end' },
    {
      id: 'ca_end',
      effects: [
        { type: 'objective', mission: 'm_call', objective: 'confirm' },
        { type: 'message', from: 'kessler', text: 'Friedrichstraße 148, 4. OG, 14:30 Uhr. Bitte Ausweis mitbringen. – J. Kessler' },
        { type: 'email', emailId: 'mail_wrona_intro' },
        { type: 'completeMission', mission: 'm_call', outcome: 'Termin bestätigt' },
        { type: 'time', set: '11:04' },
      ],
      end: true,
    },
  ],
  'call',
);
