import { dlg } from '../../dsl';

/** MISSION: ABENDESSEN UM 20:00 (BOSS) · Night call · Home */

export const dinner_main = dlg('dinner_main', [
  {
    id: 'dn1',
    speaker: 'narrator',
    direction: 'Restaurant Lindner. Kerzen, dunkles Holz, der Kollwitzplatz hinter beschlagenen Scheiben. Dr. Kessler ist schon da. Ein Mann im Maßanzug steht auf – fester Händedruck, zu langer Blickkontakt.',
    effects: [{ type: 'flag', flag: 'dinner_started' }, { type: 'objective', mission: 'm_dinner', objective: 'go' }, { type: 'time', set: '20:02' }],
    next: 'dn2',
  },
  {
    id: 'dn2',
    speaker: 'fink',
    text: 'Frau Dr. Kessler! Und Sie müssen die Geheimwaffe aus Polen sein. Tobias Fink. Setzen Sie sich – ich habe schon einen Riesling bestellt.',
    gloss: 'Pani mecenas! A Pan/Pani to pewnie tajna broń z Polski. Tobias Fink. Proszę siadać – zamówiłem już rieslinga.',
    next: 'dn3',
  },
  {
    id: 'dn3',
    speaker: 'fink',
    text: 'Und, wie gefällt Ihnen Berlin bisher? Erster Tag, habe ich gehört?',
    gloss: 'I jak się Panu/Pani podoba Berlin? Pierwszy dzień, słyszałem?',
    next: 'dn4',
  },
  {
    id: 'dn4',
    speaker: 'player',
    input: {
      task: 'Small Talk: Erzählen Sie Herrn Fink kurz von Ihrem ersten Tag.',
      taskGloss: 'Small talk: opowiedz krótko o pierwszym dniu.',
      mode: 'speak',
      skill: 'speaking',
      register: 'formal',
      targets: ['perfekt-sein', 'konnektoren', 'v2-inversion'],
      required: [
        { id: 'content', label: 'etwas über den Tag', patterns: ['tag', 'berlin', 'heute', 'morgen', 'stadt', 'bahn', 's-bahn', 'kaffee', 'wohnung', 'kiez', 'kreuzberg', 'buero', 'kanzlei'] },
        { id: 'eval', label: 'eine Bewertung', patterns: ['gut', 'schoen', 'toll', 'spannend', 'aufregend', 'anstrengend', 'interessant', 'chaotisch', 'beeindruckend', 'gefaellt', 'lang', 'intensiv', 'super', 'wunderbar', 'verrueckt', 'stressig'] },
      ],
      bonuses: [
        { pattern: String.raw`\b(aber|allerdings|trotzdem|obwohl|wenn auch)\b`, dimension: 'style', note: 'Differenziert statt nur „gut“', weight: 15 },
        { pattern: String.raw`(bin|habe|hat)[^.]*(angekommen|gefahren|eingestiegen|kennengelernt|getrunken|bekommen|gefunden|erlebt|gesehen)`, dimension: 'naturalness', note: 'Erzählt im Perfekt', weight: 12 },
        { pattern: String.raw`falsche[n]? (s-bahn|zug|gleis|richtung)`, dimension: 'idiomaticity', note: 'Selbstironie – kommt am Tisch gut an', weight: 20 },
        { pattern: String.raw`danke(,| der)? (sehr |der )?nachfrage|danke,? sehr gut`, dimension: 'register', note: 'Souveräne Einleitung', weight: 10 },
      ],
      models: ['Danke, sehr gut – wenn auch etwas chaotisch: Heute Morgen bin ich gleich in die falsche S-Bahn eingestiegen, aber inzwischen habe ich eine Wohnung und den besten Cappuccino in Kreuzberg gefunden.'],
      onSuccess: 'dn5s',
      onPartial: 'dn5p',
      onFail: 'dn5f',
    },
  },
  {
    id: 'dn5s',
    speaker: 'fink',
    text: 'Ha! Sehr gut. Berlin testet jeden am ersten Tag. Sie haben bestanden, würde ich sagen.',
    gloss: 'Ha! Bardzo dobrze. Berlin testuje każdego pierwszego dnia. Zdał Pan / zdała Pani, powiedziałbym.',
    effects: [{ type: 'rel', npc: 'fink', delta: 6 }, { type: 'objective', mission: 'm_dinner', objective: 'talk' }],
    next: 'dn6',
  },
  { id: 'dn5p', speaker: 'fink', text: 'Schön, schön. Berlin ist eben Berlin.', gloss: 'Ładnie, ładnie. Berlin to Berlin.', effects: [{ type: 'objective', mission: 'm_dinner', objective: 'talk' }], next: 'dn6' },
  { id: 'dn5f', speaker: 'fink', text: 'Ah … ja. Berlin ist groß, nicht wahr?', gloss: 'Aha… tak. Berlin jest duży, prawda?', effects: [{ type: 'rel', npc: 'fink', delta: -1 }, { type: 'objective', mission: 'm_dinner', objective: 'talk' }], next: 'dn6' },
  {
    id: 'dn6',
    speaker: 'fink',
    direction: 'Der Hauptgang kommt. Fink legt eine Ledermappe neben den Teller.',
    listening: true,
    skill: 'listening',
    text: 'Also, zum Geschäft. Herr Wrona kommt um neun. Er unterschreibt, wir trinken ein Glas, alle sind glücklich. Die polnische Fassung ist doch nur eine Arbeitsübersetzung – maßgeblich ist die deutsche. Richtig, Frau Kessler?',
    gloss: 'No to do rzeczy. Pan Wrona przyjdzie o dziewiątej. Podpisze, wypijemy kieliszek, wszyscy zadowoleni. Polska wersja to tylko tłumaczenie robocze – wiążąca jest niemiecka. Prawda, pani Kessler?',
    next: 'dn7',
  },
  {
    id: 'dn7',
    speaker: 'kessler',
    text: 'Richtig. Und genau deshalb hat {g:mein neuer Kollege|meine neue Kollegin|unser neues Teammitglied} etwas dazu zu sagen.',
    gloss: 'Zgadza się. I właśnie dlatego nasz nowy członek zespołu ma coś do powiedzenia.',
    direction: 'Sie sieht Sie an. Das Zeichen.',
    next: 'dn8',
  },
  {
    id: 'dn8',
    speaker: 'player',
    input: {
      task: 'Erklären Sie Herrn Fink sachlich die Abweichungen und machen Sie einen Vorschlag, wie man vor der Unterschrift damit umgeht.',
      taskGloss: 'Wyjaśnij rzeczowo rozbieżności i zaproponuj, co zrobić przed podpisaniem. Dyplomatycznie.',
      mode: 'speak',
      skill: 'negotiation',
      register: 'formal',
      timeLimitSec: 240,
      targets: ['verhandeln', 'hoeflichkeit-k2', 'konnektoren', 'gen-prep'],
      required: [
        { id: 'diff', label: 'die Abweichung(en) benennen', patterns: ['abweich', 'unterschied', 'stimmt nicht', 'nicht ueberein', 'falsch', String.raw`25[.\s]?000`, String.raw`250[.\s]?000`, 'vertragsstrafe', '2026', '2027', 'null'] },
        { id: 'proposal', label: 'einen Vorschlag machen', patterns: ['vorschlag', 'schlage vor', 'schlagen vor', 'koennten wir', 'sollten wir', 'korrigier', 'berichtig', 'anpass', 'zusatzvereinbarung', 'nachtrag', 'verschieb', 'neue uebersetzung', 'klarstell', 'festhalten', 'aendern'] },
      ],
      errors: [
        {
          pattern: String.raw`betrug|betruegen|luege|luegen|abzocke|verarsch|absicht`,
          target: 'verhandeln',
          category: 'register',
          severity: 2,
          message: 'Vorwurf statt Sachlichkeit. In einer Verhandlung schwächt das Ihre Position – bleiben Sie bei Fakten und Lösungen.',
        },
      ],
      bonuses: [
        { pattern: String.raw`\b(wuerden|koennten|waeren|haetten|wuerde)\b`, dimension: 'naturalness', note: 'Konjunktiv II – diplomatisch', weight: 15 },
        { pattern: String.raw`\b(allerdings|jedoch|dennoch|gleichwohl)\b`, dimension: 'style', note: 'Einschränkender Konnektor', weight: 15 },
        { pattern: String.raw`das ist richtig|da haben sie recht|das stimmt|selbstverstaendlich`, dimension: 'register', note: 'Erst zustimmen, dann einschränken', weight: 12 },
        { pattern: String.raw`im interesse|beide[rn]? seiten|alle[rn]? beteiligten|rechtssicherheit|missverstaendnis`, dimension: 'idiomaticity', note: 'Interessen beider Seiten angesprochen', weight: 20 },
        { pattern: String.raw`zusatzvereinbarung|nachtrag`, dimension: 'precision', note: 'Konkrete, umsetzbare Lösung', weight: 15 },
        { pattern: String.raw`wegen des|aufgrund de[sr]|angesichts de[sr]`, dimension: 'idiomaticity', note: 'Genitivpräposition – gehobenes Register', weight: 10 },
      ],
      models: [
        'Das ist richtig, Herr Fink. Allerdings hat Herr Wrona auf Grundlage der polnischen Fassung zugestimmt – und dort beträgt die Vertragsstrafe 25.000 statt 250.000 Euro; außerdem greift die Ausstiegsklausel ein Jahr früher. Im Interesse beider Seiten würden wir vorschlagen, diese Punkte heute Abend in einer kurzen Zusatzvereinbarung klarzustellen.',
      ],
      vocab: ['zusatzvereinbarung', 'abweichung'],
      onSuccess: 'dn9s',
      onPartial: 'dn9p',
      onFail: 'dn9f',
    },
  },
  {
    id: 'dn9s',
    speaker: 'fink',
    direction: 'Fink legt die Gabel ab. Eine Pause, die zwei Sekunden zu lang ist.',
    text: '… Sie haben Ihre Hausaufgaben gemacht. Gut. Aber verschieben geht nicht – morgen um achtzehn Uhr schließt das Transferfenster.',
    gloss: '… Odrobił Pan / odrobiła Pani lekcje. Dobrze. Ale przełożyć się nie da – jutro o 18:00 zamyka się okno transferowe.',
    effects: [
      { type: 'rel', npc: 'fink', delta: 4 },
      { type: 'rel', npc: 'kessler', delta: 6 },
      { type: 'objective', mission: 'm_dinner', objective: 'negotiate' },
      { type: 'memory', npc: 'fink', text: 'Hat beim Abendessen sachlich und diplomatisch verhandelt.' },
    ],
    next: 'dn10',
  },
  {
    id: 'dn9p',
    speaker: 'fink',
    text: 'Ich verstehe nicht ganz, worauf Sie hinauswollen. Ein paar Zahlen in einer Übersetzung …',
    gloss: 'Nie do końca rozumiem, do czego Pan/Pani zmierza. Parę liczb w tłumaczeniu…',
    next: 'dn9p2',
  },
  {
    id: 'dn9p2',
    speaker: 'kessler',
    text: 'Eine Null, Tobias. In Paragraf sieben fehlt eine Null. Und Paragraf neun stimmt auch nicht.',
    gloss: 'Jedno zero, Tobias. W paragrafie siódmym brakuje zera. A paragraf dziewiąty też się nie zgadza.',
    next: 'dn9p3',
  },
  {
    id: 'dn9p3',
    speaker: 'fink',
    text: 'Hm. Aber verschieben geht nicht – morgen um achtzehn Uhr schließt das Transferfenster.',
    gloss: 'Hm. Ale przełożyć się nie da – jutro o 18:00 zamyka się okno transferowe.',
    effects: [{ type: 'rel', npc: 'kessler', delta: 1 }, { type: 'objective', mission: 'm_dinner', objective: 'negotiate' }],
    next: 'dn10',
  },
  {
    id: 'dn9f',
    speaker: 'kessler',
    text: 'Ich übernehme. Tobias, die polnische Fassung weicht in Paragraf sieben und neun erheblich ab.',
    gloss: 'Przejmuję. Tobias, polska wersja istotnie odbiega w paragrafach siódmym i dziewiątym.',
    effects: [{ type: 'rel', npc: 'kessler', delta: -3 }, { type: 'memory', npc: 'kessler', text: 'Musste beim Abendessen übernehmen.' }],
    next: 'dn9p3',
  },
  {
    id: 'dn10',
    speaker: 'player',
    direction: 'Alle sehen Sie an. Die Uhr über der Bar: 20:41.',
    timer: 25,
    timeoutNext: 'dn_timeout',
    choices: [
      {
        text: 'Dann schlage ich vor, dass wir § 7 und § 9 noch heute Abend in einer Zusatzvereinbarung festhalten – auf Deutsch und auf Polnisch. Herr Wrona unterschreibt beides.',
        quality: 'professional',
        targets: ['verhandeln', 'nebensatz-verbend'],
        next: 'dn11a',
      },
      { text: 'Dann soll er eben morgen unterschreiben.', quality: 'understandable', feedback: 'Zu salopp – und das Problem mit der Frist bleibt ungelöst.', next: 'dn11b' },
      { text: 'Gut, dann unterschreibt er heute so, wie es ist.', quality: 'correct', feedback: 'Sprachlich korrekt. Inhaltlich gegen die Interessen Ihres Mandanten.', next: 'dn11c' },
    ],
  },
  {
    id: 'dn11a',
    speaker: 'fink',
    text: '… Einverstanden. Frau Kessler, wo haben Sie diese Person gefunden?',
    gloss: '… Zgoda. Pani Kessler, gdzie pani znalazła tę osobę?',
    effects: [{ type: 'rel', npc: 'kessler', delta: 8 }, { type: 'rel', npc: 'fink', delta: 3 }, { type: 'flag', flag: 'dinner_amendment' }, { type: 'skill', skill: 'negotiation', delta: 6 }],
    next: 'dn11a2',
  },
  { id: 'dn11a2', speaker: 'kessler', text: 'Am Hauptbahnhof, Tobias. Auf dem richtigen Gleis.', gloss: 'Na dworcu głównym, Tobias. Na właściwym peronie.', next: 'dn12' },
  {
    id: 'dn11b',
    speaker: 'fink',
    text: 'Morgen, achtzehn Uhr – das ist Harakiri. Aber gut: morgen früh, neun Uhr, mit korrigierter Übersetzung.',
    gloss: 'Jutro, 18:00 – to harakiri. Ale dobrze: jutro rano, dziewiąta, z poprawionym tłumaczeniem.',
    effects: [{ type: 'rel', npc: 'kessler', delta: 1 }, { type: 'rel', npc: 'fink', delta: -3 }, { type: 'flag', flag: 'dinner_postponed' }],
    next: 'dn12',
  },
  {
    id: 'dn11c',
    speaker: 'kessler',
    direction: 'Dr. Kessler legt ihre Hand flach auf den Tisch.',
    text: 'Nein. Das tut er nicht. Wir bereiten eine Zusatzvereinbarung vor – heute Abend.',
    gloss: 'Nie. Nie podpisze. Przygotujemy aneks – jeszcze dziś.',
    effects: [{ type: 'rel', npc: 'kessler', delta: -8 }, { type: 'flag', flag: 'dinner_overridden' }, { type: 'memory', npc: 'kessler', text: 'Wollte den Mandanten mit dem fehlerhaften Vertrag unterschreiben lassen.' }],
    next: 'dn12',
  },
  {
    id: 'dn_timeout',
    speaker: 'kessler',
    direction: 'Sie zögern einen Moment zu lange.',
    text: 'Wir halten Paragraf sieben und neun heute Abend in einer Zusatzvereinbarung fest, Tobias.',
    gloss: 'Zapiszemy paragrafy siódmy i dziewiąty w aneksie jeszcze dziś, Tobias.',
    effects: [{ type: 'rel', npc: 'kessler', delta: -2 }, { type: 'skill', skill: 'pressure', delta: -4 }, { type: 'flag', flag: 'dinner_amendment' }],
    next: 'dn12',
  },
  {
    id: 'dn12',
    speaker: 'narrator',
    direction: '21:10. Tomasz Wrona kommt – Kapuzenpullover, Blick aufs Handy, nervös. Er setzt sich neben Sie und flüstert auf Polnisch: „Co się dzieje? Pan Fink wygląda na wkurzonego.“',
    next: 'dn13',
  },
  {
    id: 'dn13',
    speaker: 'kessler',
    listening: true,
    skill: 'listening',
    text: 'Sagen Sie ihm bitte: Die Vertragsstrafe beträgt zweihundertfünfzigtausend Euro, nicht fünfundzwanzigtausend. Wir halten das in einer Zusatzvereinbarung fest, die er zusammen mit dem Vertrag unterschreibt.',
    gloss: 'Proszę mu powiedzieć: kara umowna wynosi 250 000 euro, nie 25 000. Zapiszemy to w aneksie, który podpisze razem z umową.',
    next: 'dn14',
  },
  {
    id: 'dn14',
    speaker: 'player',
    input: {
      task: 'Dolmetschen Sie für Herrn Wrona ins Polnische.',
      taskGloss: 'Przetłumacz ustnie panu Wronie na polski.',
      mode: 'translate',
      skill: 'translation',
      register: 'any',
      source: { lang: 'de', text: 'Die Vertragsstrafe beträgt 250.000 Euro, nicht 25.000. Wir halten das in einer Zusatzvereinbarung fest, die er zusammen mit dem Vertrag unterschreibt.' },
      targets: ['term-vertragsstrafe', 'uebersetzung-zahlen'],
      checkNumbers: false,
      required: [
        { id: 'amount', label: '250 000 (nicht 25 000)', patterns: ['250', 'dwieście pięćdziesiąt', 'dwiescie piecdziesiat'] },
        { id: 'amendment', label: 'aneks / porozumienie dodatkowe', patterns: ['aneks', 'porozumieni', 'umow\\w* dodatkow', 'dodatkow\\w* (umow|porozumieni|ustaleni)'] },
        { id: 'sign', label: 'podpisze (unterschreibt)', patterns: ['podpis'] },
      ],
      terms: [
        {
          term: 'Vertragsstrafe → kara umowna',
          accept: [String.raw`kar\w* umown`],
          reject: [{ pattern: 'grzywn', message: '„grzywna“ = Geldstrafe (Strafrecht). Vertragsstrafe = „kara umowna“.' }],
        },
      ],
      bonuses: [
        { pattern: String.raw`wynosi`, dimension: 'idiomaticity', note: '„wynosi“ – natürlich für Beträge', weight: 15 },
        { pattern: String.raw`pan(a|u)? |proszę pana`, dimension: 'register', note: 'Höfliche Anrede im Polnischen', weight: 8 },
      ],
      models: ['Kara umowna wynosi 250 000 euro, a nie 25 000. Zapiszemy to w aneksie, który podpisze Pan razem z umową.'],
      onSuccess: 'dn15s',
      onPartial: 'dn15p',
      onFail: 'dn15f',
    },
  },
  {
    id: 'dn15s',
    speaker: 'wrona',
    speakerName: 'Tomasz Wrona',
    text: 'Dziękuję. Teraz rozumiem. … Danke.',
    audio: false,
    gloss: 'Danke. Jetzt verstehe ich. … Danke.',
    effects: [{ type: 'flag', flag: 'wrona_trust' }, { type: 'skill', skill: 'translation', delta: 4 }],
    next: 'dn16',
  },
  { id: 'dn15p', speaker: 'wrona', speakerName: 'Tomasz Wrona', text: 'Czyli… dwieście pięćdziesiąt tysięcy? I podpisuję jakiś aneks?', audio: false, gloss: 'Also … 250.000? Und ich unterschreibe irgendeinen Nachtrag?', next: 'dn16' },
  { id: 'dn15f', speaker: 'kessler', text: 'Er sieht verwirrt aus. Wir erklären es ihm gleich noch einmal – in Ruhe.', gloss: 'Wygląda na zdezorientowanego. Zaraz wyjaśnimy mu jeszcze raz – spokojnie.', effects: [{ type: 'rel', npc: 'kessler', delta: -1 }], next: 'dn16' },
  {
    id: 'dn16',
    speaker: 'narrator',
    direction: '21:40. Die Papiere sind unterschrieben – oder vertagt. Fink zahlt, ohne auf die Rechnung zu sehen. Draußen hat es angefangen zu regnen.',
    effects: [
      { type: 'completeMission', mission: 'm_dinner', outcome: 'Verhandlung überstanden' },
      { type: 'time', set: '21:47' },
      { type: 'weather', weather: 'rain' },
      { type: 'moveTo', location: 'spree' },
      { type: 'call', dialogue: 'call_lukas', from: 'lukas', delayMs: 3500 },
    ],
    end: true,
  },
]);

export const dinner_table = dlg('dinner_table', [
  { id: 't0', branch: [{ condition: { all: [{ mission: 'm_dinner', status: 'active' }, { flag: 'dinner_started', is: false }] }, next: '@dinner_main' }], next: 't1' },
  { id: 't1', speaker: 'narrator', direction: 'Der Tisch ist abgeräumt. Ein Kellner poliert Gläser und ignoriert Sie professionell.', end: true },
]);

export const call_lukas = dlg(
  'call_lukas',
  [
    {
      id: 'nl1',
      speaker: 'lukas',
      listening: true,
      skill: 'listening',
      rate: 1.15,
      text: 'Hey, sorry, dass ich so spät anrufe. Hast du schon die Nachrichten gesehen? Ein Journalist vom Hauptstadtkurier hat die polnische Vertragsfassung. Mit der falschen Vertragsstrafe. Morgen steht’s in der Zeitung.',
      gloss: 'Hej, sorry, że dzwonię tak późno. Widziałeś/aś wiadomości? Dziennikarz z „Hauptstadtkurier” ma polską wersję umowy. Z błędną karą umowną. Jutro będzie w gazecie.',
      next: 'nl2',
    },
    {
      id: 'nl2',
      speaker: 'lukas',
      listening: true,
      skill: 'listening',
      text: 'Jana will uns morgen um elf im Büro. Das wird ein langer Tag. Bist du dabei?',
      gloss: 'Jana chce nas jutro o jedenastej w biurze. To będzie długi dzień. Wchodzisz w to?',
      next: 'nl3',
    },
    {
      id: 'nl3',
      speaker: 'player',
      input: {
        task: 'Antworten Sie Lukas.',
        taskGloss: 'Odpowiedz Lukasowi.',
        mode: 'speak',
        skill: 'speaking',
        register: 'informal',
        targets: ['uhrzeit', 'du-sie'],
        required: [{ id: 'yes', label: 'Zusage', patterns: ['\\bja\\b', 'klar', 'natuerlich', 'bin dabei', 'auf jeden fall', 'logo', 'sicher', 'selbstverstaendlich', 'komme'] }],
        bonuses: [
          { pattern: 'bin dabei', dimension: 'idiomaticity', note: '„Ich bin dabei“ – idiomatisch', weight: 22 },
          { pattern: String.raw`um elf|11 uhr|elf uhr`, dimension: 'precision', note: 'Uhrzeit bestätigt', weight: 12 },
          { pattern: 'bis morgen', dimension: 'naturalness', note: 'Natürlicher Abschluss', weight: 12 },
        ],
        models: ['Klar, ich bin dabei. Bis morgen um elf!'],
        onSuccess: 'nl4',
        onPartial: 'nl4',
        onFail: 'nl4f',
      },
    },
    { id: 'nl4', speaker: 'lukas', text: 'Stark. Und hey – guter erster Tag. Wirklich.', gloss: 'Mocne. I hej – dobry pierwszy dzień. Serio.', effects: [{ type: 'rel', npc: 'lukas', delta: 4 }], next: 'nl_end' },
    { id: 'nl4f', speaker: 'lukas', text: 'Ich nehm das mal als Ja. Elf Uhr! Gute Nacht.', gloss: 'Uznam to za „tak”. Jedenasta! Dobranoc.', next: 'nl_end' },
    { id: 'nl_end', effects: [{ type: 'flag', flag: 'night_call_done' }], end: true },
  ],
  'call',
);

export const night_home = dlg('night_home', [
  {
    id: 'h1',
    speaker: 'narrator',
    direction: 'Tram M1, dann U8. Regen auf den Fenstern, Neonlicht auf nassem Asphalt. Kreuzberg schläft nicht. Sie gleich.',
    effects: [{ type: 'flag', flag: 'day1_done' }, { type: 'time', set: '22:31' }, { type: 'moveTo', location: 'wohnung' }],
    end: true,
  },
]);

export const home_desk = dlg('home_desk', [
  {
    id: 'd1',
    speaker: 'narrator',
    direction: 'Der Schreibtisch am Fenster. Ihr Notizbuch, Kasias altes Grammatikbuch, eine Lampe. Hier können Sie gezielt an Ihren Schwächen arbeiten.',
    effects: [{ type: 'ui', open: 'training' }],
    end: true,
  },
]);

export const home_window = dlg('home_window', [
  {
    id: 'w1',
    speaker: 'narrator',
    direction: 'Hinterhof, Kastanie, gegenüber ein Fenster mit Lichterkette. Jemand übt Trompete, schlecht. Irgendwo streitet ein Paar auf Türkisch, dann lachen beide. Das ist jetzt Ihr Blick.',
    end: true,
  },
]);

export const home_bed = dlg('home_bed', [
  {
    id: 'b0',
    branch: [
      { condition: { flag: 'day1_done', is: false }, next: 'b_not' },
      { condition: { flag: 'day2_started', is: false }, next: 'b_sleep' },
      { condition: { mission: 'm_amt', status: 'completed' }, next: 'b_tbc' },
    ],
    next: 'b_day2',
  },
  { id: 'b_not', speaker: 'narrator', direction: 'Nicht jetzt. Der Tag ist noch nicht vorbei.', end: true },
  { id: 'b_day2', speaker: 'narrator', direction: 'Später. Zuerst das Bürgeramt – Termin 09:10.', end: true },
  {
    id: 'b_tbc',
    speaker: 'narrator',
    direction: 'Die Meldebescheinigung liegt auf dem Tisch. Um elf wartet Dr. Kessler. Der Hauptstadtkurier hat die Geschichte online gestellt. FORTSETZUNG: 48 STUNDEN – in Produktion.',
    end: true,
  },
  {
    id: 'b_sleep',
    speaker: 'narrator',
    direction: 'Sie liegen im Dunkeln. Das Haus knackt. Irgendwo fährt die U1 über das Viadukt. Heute Morgen konnten Sie kaum eine Durchsage verstehen. Jetzt haben Sie einen Vertrag verhandelt.',
    effects: [{ type: 'advanceDay' }],
    end: true,
  },
]);
