import { dlg } from '../../dsl';

/** MISSION: DAS FALSCHE GLEIS — Hauptbahnhof, 06:42 */

export const hbf_intro = dlg('hbf_intro', [
  {
    id: 'i1',
    speaker: 'narrator',
    direction: 'Der Zug aus Warschau ist pünktlich. Sie nicht – Sie sind seit zweiundzwanzig Stunden wach. Ihr Telefon vibriert.',
    next: 'i2',
  },
  {
    id: 'i2',
    skill: 'reading',
    effects: [
      {
        type: 'message',
        from: 'kasia',
        text: 'Willkommen in Berlin!! 🎉 Nimm die S5 Richtung Strausberg bis Warschauer Straße. Dort steigst du in die U1 um, bis Kottbusser Tor. Frau Wiesner wartet um Viertel nach acht vor dem Haus (Graefestraße 12). Sei pünktlich – sie ist… sehr preußisch. 😅 PS: Frag sie nach der Wohnungsgeberbestätigung – ohne die kannst du dich nicht anmelden! Und: Ab jetzt nur Deutsch! K.',
      },
      { type: 'objective', mission: 'm_platform', objective: 'read_sms' },
    ],
    document: {
      kind: 'sms',
      title: 'Kasia',
      lines: [
        { text: 'Willkommen in Berlin!! 🎉' },
        { text: 'Nimm die S5 Richtung Strausberg bis Warschauer Straße. Dort steigst du in die U1 um, bis Kottbusser Tor.', highlight: true },
        { text: 'Frau Wiesner wartet um Viertel nach acht vor dem Haus (Graefestraße 12). Sei pünktlich – sie ist… sehr preußisch. 😅' },
        { text: 'PS: Frag sie nach der Wohnungsgeberbestätigung – ohne die kannst du dich nicht anmelden!' },
        { text: 'Und: Ab jetzt nur Deutsch! K.' },
      ],
    },
    next: 'i3',
  },
  {
    id: 'i3',
    speaker: 'player',
    direction: 'Antworten Sie Kasia.',
    choices: [
      { text: 'Danke! Ich bin gerade angekommen. Bis später!', quality: 'natural', targets: ['perfekt-sein'], next: 'i4a' },
      {
        text: 'Danke! Ich habe gerade angekommen. Bis später!',
        quality: 'understandable',
        targets: ['perfekt-sein'],
        feedback: '„ankommen“ bildet das Perfekt mit „sein“: Ich bin angekommen.',
        next: 'i4b',
      },
      { text: 'Dzięki! Już jestem, do zobaczenia!', gloss: '(auf Polnisch)', quality: 'incorrect', feedback: 'Kasia hat es gesagt: ab jetzt nur Deutsch.', next: 'i4c' },
    ],
  },
  { id: 'i4a', speaker: 'kasia', text: 'Super! 💪 Du schaffst das.', audio: false, next: 'i5', effects: [{ type: 'rel', npc: 'kasia', delta: 2 }] },
  { id: 'i4b', speaker: 'kasia', text: 'Du BIST angekommen 😉 Aber: super! 💪', audio: false, next: 'i5' },
  { id: 'i4c', speaker: 'kasia', text: 'DEUTSCH!! 😄 Los geht’s.', audio: false, next: 'i5', effects: [{ type: 'memory', npc: 'kasia', text: 'Hat am ersten Morgen auf Polnisch geantwortet.' }] },
  {
    id: 'i5',
    speaker: 'narrator',
    direction: 'Über Ihnen donnert ein ICE durch die Glashalle. Irgendwo hier fährt Ihre S-Bahn. Die Abfahrtstafel hängt links, der DB-Schalter rechts.',
    effects: [
      { type: 'flag', flag: 'intro_done' },
      { type: 'time', set: '06:44' },
    ],
    end: true,
  },
]);

export const hbf_board = dlg('hbf_board', [
  {
    id: 'b1',
    skill: 'reading',
    document: {
      kind: 'board',
      title: 'ABFAHRT · S-BAHN · OBERE EBENE',
      lines: [
        { text: '06:51  S7   Ahrensfelde            Gl. 16', mono: true },
        { text: '06:54  S3   Erkner                 Gl. 16', mono: true },
        { text: '06:58  S5   Strausberg Nord        Gl. 15', mono: true, highlight: true, id: 's5' },
        { text: '07:00  S5   Westkreuz              Gl. 16', mono: true },
        { text: '07:03  S9   Flughafen BER          Gl. 16', mono: true },
        { text: '+++ Achtung: Gleiswechsel wegen Bauarbeiten – bitte Durchsagen beachten +++', small: true },
      ],
    },
    next: 'b2',
  },
  {
    id: 'b2',
    speaker: 'announce',
    speakerName: 'Durchsage',
    listening: true,
    skill: 'listening',
    text: 'Achtung an Gleis 15 und 16. Wegen Bauarbeiten fährt die S5 in Richtung Strausberg Nord heute von Gleis 16. Die S5 in Richtung Westkreuz fährt heute von Gleis 15. Ich wiederhole: S5 Richtung Strausberg Nord heute von Gleis 16.',
    gloss: 'Uwaga: z powodu prac budowlanych S5 w kierunku Strausberg Nord odjeżdża dziś z toru 16, a S5 w kierunku Westkreuz z toru 15.',
    effects: [{ type: 'flag', flag: 'heard_announcement' }],
    next: 'b3',
  },
  {
    id: 'b3',
    speaker: 'player',
    choices: [
      { text: '(Die Durchsage noch einmal hören)', next: 'b2' },
      { text: '(Weitergehen)', next: 'b4' },
    ],
  },
  { id: 'b4', end: true },
]);

export const hbf_pohl = dlg('hbf_pohl', [
  { id: 'p0', branch: [{ condition: { flag: 'talked_pohl' }, next: 'p_again' }], next: 'p1' },
  {
    id: 'p_again',
    speaker: 'pohl',
    text: 'Gleis sechzehn. Immer noch. Die fährt gleich!',
    gloss: 'Tor szesnasty. Nadal. Zaraz odjeżdża!',
    end: true,
  },
  {
    id: 'p1',
    speaker: 'pohl',
    direction: 'Ein Mann in roter DB-Jacke sortiert Fahrpläne. Er sieht nicht auf.',
    text: 'Morgen. Was kann ich für Sie tun?',
    gloss: 'Dzień dobry. W czym mogę pomóc?',
    effects: [{ type: 'flag', flag: 'talked_pohl' }],
    next: 'p2',
  },
  {
    id: 'p2',
    speaker: 'player',
    input: {
      task: 'Fragen Sie Herrn Pohl, von welchem Gleis die S5 Richtung Strausberg fährt.',
      taskGloss: 'Zapytaj, z którego toru odjeżdża S5 w kierunku Strausberg.',
      placeholder: 'Entschuldigung, …',
      mode: 'speak',
      skill: 'speaking',
      register: 'formal',
      targets: ['w-fragen', 'dativ-praep', 'hoeflichkeit-k2', 'du-sie'],
      required: [
        { id: 'line', label: 'die Linie S5 / Richtung Strausberg', patterns: ['s ?5', 'strausberg', 's-bahn'] },
        { id: 'where', label: 'die Frage nach dem Gleis', patterns: ['gleis', 'bahnsteig', 'wo (faehrt|fahrt|halt|ist)', 'von wo', 'abfahrt', 'wo finde'] },
      ],
      errors: [
        {
          pattern: String.raw`von (welche|welcher|welches|welchen) gleis\b`,
          target: 'dativ-praep',
          category: 'cases',
          severity: 2,
          message: '„von“ + Dativ: von welchem Gleis (das Gleis → dem Gleis).',
          pl: '„von“ wymaga celownika: von welchem Gleis.',
          fix: 'von welchem Gleis',
        },
        {
          pattern: String.raw`\bwo ist (die )?s ?5\b`,
          category: 'vocabulary',
          severity: 1,
          message: '„Wo ist die S5?“ versteht man – präziser fragt man nach dem Gleis: „Von welchem Gleis fährt die S5?“',
        },
      ],
      bonuses: [
        { pattern: 'entschuldig', dimension: 'register', note: 'Höflicher Einstieg mit „Entschuldigung“', weight: 10 },
        { pattern: 'guten morgen|morgen,', dimension: 'register', note: 'Gruß erwidert', weight: 5 },
        { pattern: 'koennten sie|wuerden sie|koennen sie mir sagen', dimension: 'naturalness', note: 'Höfliche Frage', weight: 20 },
        { pattern: 'von welchem gleis', dimension: 'idiomaticity', note: '„Von welchem Gleis“ – präzise und idiomatisch', weight: 30 },
        { pattern: 'richtung strausberg', dimension: 'precision', note: 'Richtung genannt', weight: 10 },
      ],
      models: [
        'Guten Morgen! Könnten Sie mir sagen, von welchem Gleis die S5 Richtung Strausberg fährt?',
        'Entschuldigung, von welchem Gleis fährt die S5 nach Strausberg?',
      ],
      vocab: ['gleis', 'richtung', 'abfahren'],
      onSuccess: 'p3s',
      onPartial: 'p3p',
      onFail: 'p3f',
    },
  },
  {
    id: 'p3s',
    speaker: 'pohl',
    text: 'Die S5 nach Strausberg? Heute von Gleis sechzehn – Bauarbeiten. Ganz oben, auf der obersten Ebene. Sie haben noch sechs Minuten.',
    gloss: 'S5 do Strausberg? Dziś z toru 16 – prace budowlane. Na samej górze. Ma Pan/Pani jeszcze sześć minut.',
    skill: 'listening',
    effects: [{ type: 'flag', flag: 'knows_16' }, { type: 'rel', npc: 'pohl', delta: 5 }, { type: 'objective', mission: 'm_platform', objective: 'find_s5' }],
    next: 'p4',
  },
  {
    id: 'p3p',
    speaker: 'pohl',
    text: 'Wie bitte? … Ach so, die S5. Richtung Strausberg fährt die heute von Gleis sechzehn, nicht fünfzehn. Oben.',
    gloss: 'Słucham? … Aha, S5. W kierunku Strausberg dziś z toru 16, nie 15. Na górze.',
    skill: 'listening',
    effects: [{ type: 'flag', flag: 'knows_16' }, { type: 'objective', mission: 'm_platform', objective: 'find_s5' }],
    next: 'p4',
  },
  {
    id: 'p3f',
    speaker: 'pohl',
    text: 'Tut mir leid, das habe ich nicht verstanden. Wohin möchten Sie denn?',
    gloss: 'Przykro mi, nie zrozumiałem. Dokąd chce Pan/Pani jechać?',
    next: 'p3f_c',
  },
  {
    id: 'p3f_c',
    speaker: 'player',
    choices: [
      { text: 'Nach Kreuzberg. Zum Kottbusser Tor.', quality: 'natural', targets: ['dativ-praep'], next: 'p3f2' },
      { text: 'Zu Kreuzberg, bitte.', quality: 'understandable', targets: ['dativ-praep'], feedback: 'Bei Stadtteilen und Städten: „nach Kreuzberg“. „zu“ steht bei Personen und Gebäuden: zum Bahnhof, zu Kasia.', next: 'p3f2' },
      { text: 'S5 … Strausberg?', quality: 'understandable', next: 'p3f2' },
    ],
  },
  {
    id: 'p3f2',
    speaker: 'pohl',
    rate: 0.8,
    text: 'Dann nehmen Sie die S5 Richtung Strausberg. Heute von Gleis sech-zehn. Sechzehn. Oben.',
    gloss: 'To proszę wziąć S5 w kierunku Strausberg. Dziś z toru szesnaście. Na górze.',
    skill: 'listening',
    effects: [{ type: 'flag', flag: 'knows_16' }, { type: 'objective', mission: 'm_platform', objective: 'find_s5' }],
    next: 'p4',
  },
  {
    id: 'p4',
    speaker: 'pohl',
    text: 'Haben Sie schon eine Fahrkarte?',
    gloss: 'Ma Pan/Pani już bilet?',
    next: 'p4c',
  },
  {
    id: 'p4c',
    speaker: 'player',
    choices: [
      { text: 'Nein, noch nicht. Welche Fahrkarte brauche ich bis Kottbusser Tor?', quality: 'natural', targets: ['w-fragen'], next: 'p5' },
      {
        text: 'Nein. Ich brauche eine Fahrkarte für nach Kreuzberg.',
        quality: 'understandable',
        targets: ['dativ-praep'],
        feedback: '„für nach“ ist doppelt. Natürlich: „eine Fahrkarte nach Kreuzberg“.',
        next: 'p5',
      },
      { text: 'Ja, danke.', quality: 'correct', next: 'p6', effects: [{ type: 'flag', flag: 'no_ticket' }] },
    ],
  },
  {
    id: 'p5',
    speaker: 'pohl',
    text: 'Einzelfahrschein AB. Am Automaten da drüben oder in der App. AB gilt im ganzen Stadtgebiet – Kreuzberg ist drin.',
    gloss: 'Bilet jednorazowy AB. W automacie tam albo w aplikacji. Strefa AB obejmuje całe miasto – Kreuzberg też.',
    skill: 'listening',
    effects: [{ type: 'item', item: 'ticket_ab' }],
    next: 'p5c',
  },
  {
    id: 'p5c',
    speaker: 'player',
    choices: [
      { text: 'Vielen Dank für Ihre Hilfe!', quality: 'natural', targets: ['dativ-praep'], next: 'p7', effects: [{ type: 'rel', npc: 'pohl', delta: 3 }] },
      { text: 'Danke, tschüss!', quality: 'correct', next: 'p7' },
    ],
  },
  { id: 'p6', speaker: 'pohl', text: 'Na dann. Gute Fahrt.', gloss: 'No to dobrej podróży.', end: true },
  { id: 'p7', speaker: 'pohl', text: 'Gute Fahrt. Und willkommen in Berlin.', gloss: 'Dobrej podróży. I witamy w Berlinie.', end: true },
]);

export const hbf_platforms = dlg('hbf_platforms', [
  {
    id: 'pl1',
    speaker: 'narrator',
    direction: 'Rolltreppe nach oben. Zwei Bahnsteige, zwei S-Bahnen, beide rot-gelb, beide mit „S5“ beschriftet. Ein Pfiff. Eine davon fährt gleich ab.',
    next: 'pl2',
  },
  {
    id: 'pl2',
    speaker: 'player',
    direction: 'Welches Gleis?',
    timer: 15,
    timeoutNext: 'pl_miss',
    choices: [
      { text: 'Gleis 15', next: 'pl15' },
      { text: 'Gleis 16', next: 'pl16' },
    ],
  },
  {
    id: 'pl_miss',
    speaker: 'narrator',
    direction: 'Die Türen schließen. Beide Züge fahren ab. Die nächsten kommen in zehn Minuten. Ihr Puls auch.',
    effects: [{ type: 'skill', skill: 'pressure', delta: -4 }],
    next: 'pl2b',
  },
  {
    id: 'pl2b',
    speaker: 'player',
    direction: 'Zehn Minuten später. Welches Gleis?',
    choices: [
      { text: 'Gleis 15', next: 'pl15' },
      { text: 'Gleis 16', next: 'pl16' },
    ],
  },
  {
    id: 'pl16',
    speaker: 'announce',
    speakerName: 'Ansage im Zug',
    listening: true,
    skill: 'listening',
    text: 'S5 nach Strausberg Nord. Nächste Station: Friedrichstraße. Übergang zur U6 und zum Regionalverkehr.',
    gloss: 'S5 do Strausberg Nord. Następna stacja: Friedrichstraße.',
    effects: [{ type: 'objective', mission: 'm_platform', objective: 'board' }, { type: 'flag', flag: 'right_train' }],
    next: 'pl16b',
  },
  {
    id: 'pl16b',
    speaker: 'narrator',
    direction: 'Richtig. Die Stadt zieht vorbei: der Reichstag im Morgendunst, die Spree, die Kuppel des Doms. Niemand im Waggon spricht. Alle schauen aufs Handy. Sie sind angekommen.',
    branch: [{ condition: { flag: 'no_ticket' }, next: 'kontrolle' }],
    next: 'transfer',
  },
  {
    id: 'pl15',
    speaker: 'announce',
    speakerName: 'Ansage im Zug',
    listening: true,
    skill: 'listening',
    text: 'S5 nach Westkreuz. Nächste Station: Bellevue.',
    gloss: 'S5 do Westkreuz. Następna stacja: Bellevue.',
    effects: [{ type: 'flag', flag: 'wrong_train' }, { type: 'skill', skill: 'listening', delta: -3 }],
    next: 'pl15b',
  },
  {
    id: 'pl15b',
    speaker: 'narrator',
    direction: 'Bellevue? Das Schloss Bellevue liegt … im Westen. Sie fahren in die falsche Richtung. Die Durchsage in der Halle – das war es also.',
    next: 'pl15c',
  },
  {
    id: 'pl15c',
    speaker: 'narrator',
    direction: 'Aussteigen, zurückfahren. Sie werden etwa fünfundzwanzig Minuten zu spät sein. Frau Wiesners Nummer steht in Kasias alter Nachricht.',
    next: 'pl15sms',
  },
  {
    id: 'pl15sms',
    speaker: 'player',
    input: {
      task: 'Schreiben Sie Frau Wiesner eine kurze SMS: Sie kommen später, weil Sie in die falsche S-Bahn eingestiegen sind. Nennen Sie die neue Uhrzeit (ca. 8:40).',
      taskGloss: 'Napisz SMS: spóźnisz się, bo wsiadłeś/wsiadłaś do złej kolejki. Podaj nową godzinę (ok. 8:40).',
      mode: 'write',
      skill: 'writing',
      register: 'formal',
      targets: ['nebensatz-verbend', 'perfekt-sein', 'du-sie', 'uhrzeit'],
      required: [
        { id: 'late', label: 'dass Sie später kommen', patterns: ['spaeter', 'verspaet', 'zu spaet', 'nicht puenktlich'] },
        { id: 'why', label: 'der Grund (falsche S-Bahn)', patterns: ['falsch', 'verkehrt', 'richtung', 'westkreuz', 'bellevue'] },
        { id: 'time', label: 'die neue Uhrzeit', patterns: [String.raw`8[:.]? ?40`, 'acht uhr vierzig', 'zwanzig vor neun', '8 uhr 40', String.raw`25 minuten`, 'fuenfundzwanzig minuten', String.raw`halbe stunde`] },
      ],
      bonuses: [
        { pattern: 'entschuldig|tut mir (sehr |wirklich )?leid', dimension: 'register', note: 'Entschuldigung formuliert', weight: 10 },
        { pattern: 'guten morgen,? frau wiesner|sehr geehrte frau wiesner|liebe frau wiesner', dimension: 'register', note: 'Korrekte Anrede', weight: 10 },
        { pattern: String.raw`weil ich [^.,!?]*eingestiegen bin`, dimension: 'idiomaticity', note: 'Nebensatz mit Verbendstellung und Perfekt mit „sein“', weight: 30 },
        { pattern: 'viele gruesse|mit freundlichen gruessen|beste gruesse', dimension: 'style', note: 'Grußformel', weight: 10 },
      ],
      models: ['Guten Morgen, Frau Wiesner, es tut mir sehr leid: Ich komme etwa 25 Minuten später, weil ich in die falsche S-Bahn eingestiegen bin. Ich bin gegen 8:40 Uhr da. Viele Grüße, {first} {last}'],
      onSuccess: 'pl15s',
      onPartial: 'pl15p',
      onFail: 'pl15f',
    },
  },
  {
    id: 'pl15s',
    speaker: 'wiesner',
    text: 'Gut. 8:40 Uhr. Nicht später. – E. Wiesner',
    audio: false,
    effects: [{ type: 'flag', flag: 'late_informed' }, { type: 'message', from: 'wiesner', text: 'Gut. 8:40 Uhr. Nicht später. – E. Wiesner' }],
    next: 'late_route',
  },
  {
    id: 'pl15p',
    speaker: 'wiesner',
    text: 'Ich verstehe nicht ganz, wann Sie kommen. Ich warte bis 8:45 Uhr. – E. Wiesner',
    audio: false,
    effects: [{ type: 'flag', flag: 'late_informed' }, { type: 'rel', npc: 'wiesner', delta: -2 }, { type: 'message', from: 'wiesner', text: 'Ich verstehe nicht ganz, wann Sie kommen. Ich warte bis 8:45 Uhr. – E. Wiesner' }],
    next: 'late_route',
  },
  {
    id: 'pl15f',
    speaker: 'narrator',
    direction: 'Keine Antwort. Zwei graue Häkchen. Frau Wiesner hat die Nachricht gelesen – und nicht verstanden.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: -5 }],
    next: 'late_route',
  },
  {
    id: 'late_route',
    speaker: 'narrator',
    direction: 'Zurück zum Hauptbahnhof, diesmal Gleis 16. Friedrichstraße, Alexanderplatz, Ostbahnhof, Warschauer Straße.',
    effects: [{ type: 'flag', flag: 'late' }],
    branch: [{ condition: { flag: 'no_ticket' }, next: 'kontrolle' }],
    next: 'transfer',
  },
  {
    id: 'kontrolle',
    speaker: 'kontrolleur',
    speakerName: 'Fahrkartenkontrolle',
    direction: 'Zwei Personen in Zivil stehen auf. Ausweise an Schlüsselbändern.',
    text: 'Guten Morgen, die Fahrscheine bitte.',
    gloss: 'Dzień dobry, bilety do kontroli.',
    next: 'kontrolle_c',
  },
  {
    id: 'kontrolle_c',
    speaker: 'player',
    choices: [
      { text: 'Es tut mir leid, ich habe keine Fahrkarte. Ich bin heute Morgen erst angekommen.', quality: 'natural', targets: ['perfekt-sein'], next: 'kontrolle2' },
      { text: 'Ich habe keine Fahrkarte, weil ich bin neu hier.', quality: 'understandable', targets: ['nebensatz-verbend'], feedback: 'Nebensatz: „…, weil ich neu hier bin.“ (Verb am Ende)', next: 'kontrolle2' },
      { text: 'Sorry, no German.', quality: 'incorrect', feedback: 'Sie sprechen Deutsch. Auch unter Druck.', next: 'kontrolle2' },
    ],
  },
  {
    id: 'kontrolle2',
    speaker: 'kontrolleur',
    speakerName: 'Fahrkartenkontrolle',
    text: 'Das tut mir leid für Sie, aber ohne gültigen Fahrschein wird ein erhöhtes Beförderungsentgelt fällig: sechzig Euro. Willkommen in Berlin.',
    gloss: 'Przykro mi, ale bez ważnego biletu obowiązuje opłata dodatkowa: 60 euro. Witamy w Berlinie.',
    skill: 'listening',
    effects: [{ type: 'flag', flag: 'fined' }, { type: 'vocab', words: ['befoerderungsentgelt'], mode: 'seen' }],
    next: 'transfer',
  },
  {
    id: 'transfer',
    speaker: 'announce',
    speakerName: 'Ansage U1',
    listening: true,
    skill: 'listening',
    text: 'Warschauer Straße. Übergang zur U1. … Nächster Halt: Kottbusser Tor. Übergang zur U8.',
    gloss: 'Warschauer Straße, przesiadka do U1. … Następny przystanek: Kottbusser Tor.',
    next: 'arrive',
  },
  {
    id: 'arrive',
    speaker: 'narrator',
    direction: 'Kottbusser Tor. Tauben, Kebabduft, ein Hochbahnviadukt. Zehn Minuten zu Fuß am Landwehrkanal entlang – und Sie stehen im Graefekiez.',
    branch: [{ condition: { flag: 'late' }, next: 'arrive_late' }],
    next: 'arrive_ok',
  },
  {
    id: 'arrive_ok',
    effects: [
      { type: 'completeMission', mission: 'm_platform', outcome: 'Pünktlich angekommen' },
      { type: 'time', set: '08:09' },
      { type: 'moveTo', location: 'kreuzberg' },
    ],
    end: true,
  },
  {
    id: 'arrive_late',
    effects: [
      { type: 'completeMission', mission: 'm_platform', outcome: 'Umweg über Bellevue' },
      { type: 'time', set: '08:38' },
      { type: 'moveTo', location: 'kreuzberg' },
    ],
    end: true,
  },
]);
