import { dlg } from '../../dsl';
import type { DocumentSpec } from '../../../engine/types';

/** MISSION: DER VERTRAG — Kessler & Aydın, Friedrichstraße 148 (BOSS MISSION) */

export const CONTRACT_DE: DocumentSpec = {
  kind: 'contract',
  title: 'Arbeitsvertrag für Lizenzspieler · FC Spree Berlin 1911 e. V. – Tomasz Wrona · Deutsche Fassung',
  lines: [
    { text: '§ 4 Exklusivität', small: true },
    { text: '(1) Der Spieler verpflichtet sich, während der Vertragslaufzeit ausschließlich für den Verein tätig zu werden.', id: 'de4' },
    { text: '§ 7 Vertragsstrafe', small: true },
    { text: 'Verstößt der Spieler schuldhaft gegen seine Pflichten aus § 4, hat er an den Verein eine Vertragsstrafe in Höhe von 250.000,00 EUR zu zahlen.', id: 'de7' },
    { text: '§ 9 Vertragsbeendigung', small: true },
    { text: '(1) Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt.', id: 'de9_1' },
    { text: '(2) Der Spieler kann den Vertrag zum 30. Juni 2027 vorzeitig beenden, sofern ein aufnehmender Verein eine Ablösesumme von mindestens 4.000.000,00 EUR an den Verein zahlt.', id: 'de9_2' },
    { text: '§ 10 Vergütung', small: true },
    { text: '(1) Der Spieler erhält ein monatliches Grundgehalt in Höhe von 38.500,00 EUR brutto.', id: 'de10' },
    { text: '§ 14 Sprachfassung', small: true },
    { text: 'Maßgeblich ist ausschließlich die deutsche Fassung dieses Vertrags.', id: 'de14' },
  ],
  footer: 'Seite 3 von 11 · Entwurf · Stand: heute, 09:12 Uhr',
};

export const CONTRACT_PL: DocumentSpec = {
  kind: 'contract',
  title: 'Umowa o pracę zawodnika licencjonowanego · Tłumaczenie robocze (PL)',
  lines: [
    { text: '§ 4 Wyłączność', small: true },
    { text: '(1) Zawodnik zobowiązuje się w okresie obowiązywania umowy świadczyć usługi wyłącznie na rzecz Klubu.', id: 'pl4' },
    { text: '§ 7 Kara umowna', small: true },
    { text: 'W przypadku zawinionego naruszenia przez Zawodnika obowiązków określonych w § 4 Zawodnik zapłaci Klubowi karę umowną w wysokości 25 000,00 EUR.', id: 'pl7' },
    { text: '§ 9 Rozwiązanie umowy', small: true },
    { text: '(1) Prawo do odstąpienia od umowy z ważnej przyczyny pozostaje nienaruszone.', id: 'pl9_1' },
    { text: '(2) Zawodnik może rozwiązać umowę przed terminem z dniem 30 czerwca 2026 r., o ile nowy klub zapłaci Klubowi kwotę odstępnego w wysokości co najmniej 4 000 000,00 EUR.', id: 'pl9_2' },
    { text: '§ 10 Wynagrodzenie', small: true },
    { text: '(1) Zawodnik otrzymuje miesięczne wynagrodzenie zasadnicze w wysokości 38 500,00 EUR brutto.', id: 'pl10' },
    { text: '§ 14 Wersja językowa', small: true },
    { text: 'Wiążąca jest wyłącznie niemiecka wersja niniejszej umowy.', id: 'pl14' },
  ],
  footer: 'Tłumaczenie robocze – nie jest tłumaczeniem przysięgłym',
};

export const k_reception = dlg('k_reception', [
  {
    id: 'r1',
    speaker: 'narrator',
    direction: 'Vierter Stock. Glastür, Messingschild: KESSLER & AYDIN RECHTSANWÄLTE. Telefone, Druckerrauschen, jemand sagt „Frist“ in einem Ton, als wäre es ein Schimpfwort. Ein junger Mann mit gelockertem Krawattenknoten winkt.',
    next: 'r2',
  },
  {
    id: 'r2',
    speaker: 'lukas',
    text: 'Hey! Du bist bestimmt unsere Verstärkung aus Polen. Ich bin Lukas. Wir duzen uns hier im Team – okay für dich?',
    gloss: 'Hej! Ty pewnie jesteś naszym wsparciem z Polski. Jestem Lukas. W zespole mówimy sobie na „ty” – pasuje ci?',
    effects: [{ type: 'objective', mission: 'm_contract', objective: 'arrive' }],
    next: 'r3',
  },
  {
    id: 'r3',
    speaker: 'player',
    choices: [
      { text: 'Klar, sehr gern! Ich bin {first}. Freut mich.', quality: 'natural', targets: ['du-sie'], next: 'r4', effects: [{ type: 'rel', npc: 'lukas', delta: 5 }] },
      {
        text: 'Freut mich, Herr Brandt. Wie geht es Ihnen?',
        quality: 'understandable',
        targets: ['du-sie'],
        feedback: 'Lukas hat das „du“ angeboten. Wer weiter siezt, wirkt distanziert – oder lehnt das Angebot ab.',
        next: 'r3b',
      },
      { text: 'Okay. Ich bin {first}.', quality: 'correct', targets: ['du-sie'], next: 'r4' },
    ],
  },
  { id: 'r3b', speaker: 'lukas', text: 'Herr Brandt ist mein Vater. Lukas reicht!', gloss: 'Pan Brandt to mój ojciec. Wystarczy Lukas!', next: 'r4' },
  {
    id: 'r4',
    speaker: 'lukas',
    text: 'Jana – also Dr. Kessler – wartet im Besprechungsraum. Kleiner Tipp: Sie redet schnell, und sie hasst es, wenn man „äh“ sagt. Viel Glück!',
    gloss: 'Jana – czyli dr Kessler – czeka w sali konferencyjnej. Mała rada: mówi szybko i nie znosi, jak ktoś mówi „yyy”. Powodzenia!',
    effects: [{ type: 'flag', flag: 'k_arrived' }, { type: 'time', set: '14:28' }],
    end: true,
  },
]);

export const k_kessler = dlg('k_kessler', [
  {
    id: 'k0',
    branch: [
      { condition: { flag: 'k_arrived', is: false }, next: 'k_notyet' },
      { condition: { flag: 'briefed', is: false }, next: 'b1' },
      { condition: { all: [{ flag: 'email_sent' }, { flag: 'reported', is: false }] }, next: 'rep0' },
      { condition: { flag: 'email_sent', is: false }, next: 'k_busy' },
    ],
    next: 'k_later',
  },
  { id: 'k_notyet', speaker: 'narrator', direction: 'Die Glastür ist zu. Melden Sie sich zuerst am Empfang.', end: true },
  { id: 'k_busy', speaker: 'kessler', text: 'Die Unterlagen liegen auf Ihrem Schreibtisch. Siebzehn Uhr.', gloss: 'Dokumenty leżą na Pana/Pani biurku. Siedemnasta.', end: true },
  { id: 'k_later', speaker: 'kessler', text: 'Wir sehen uns heute Abend. Zwanzig Uhr, Restaurant Lindner.', gloss: 'Widzimy się wieczorem. 20:00, restauracja Lindner.', end: true },
  {
    id: 'b1',
    speaker: 'kessler',
    direction: 'Dr. Jana Kessler. Schwarzer Blazer, Lesebrille in der Hand, drei Handys auf dem Tisch. Sie steht nicht auf.',
    text: 'Da sind Sie. Setzen Sie sich. Kurz und knapp.',
    gloss: 'Jest Pan/Pani. Proszę usiąść. Krótko i zwięźle.',
    next: 'b2',
  },
  {
    id: 'b2',
    speaker: 'kessler',
    listening: true,
    skill: 'listening',
    text: 'Tomasz Wrona, vierundzwanzig, Innenverteidiger, wechselt von Orzeł Toruń zum FC Spree. Der Verein hat uns zwei Fassungen geschickt: die deutsche – die ist verbindlich – und eine polnische Arbeitsübersetzung. Herr Wrona hat nur die polnische gelesen.',
    gloss: 'Tomasz Wrona, 24 lata, środkowy obrońca, przechodzi z Orła Toruń do FC Spree. Klub przysłał dwie wersje: niemiecką – wiążącą – i polskie tłumaczenie robocze. Pan Wrona czytał tylko polską.',
    next: 'b3',
  },
  {
    id: 'b3',
    speaker: 'kessler',
    listening: true,
    skill: 'listening',
    text: 'Vergleichen Sie beide Fassungen, insbesondere Paragraf sieben, Vertragsstrafe, und Paragraf neun, Vertragsbeendigung. Bis siebzehn Uhr brauche ich eine kurze Zusammenfassung per E-Mail. Um zwanzig Uhr essen wir mit Herrn Fink, dem Sportdirektor. Fragen?',
    gloss: 'Proszę porównać obie wersje, zwłaszcza § 7 (kara umowna) i § 9 (rozwiązanie umowy). Do 17:00 potrzebuję krótkiego podsumowania mailem. O 20:00 kolacja z panem Finkiem, dyrektorem sportowym. Pytania?',
    next: 'b4',
  },
  {
    id: 'b4',
    speaker: 'player',
    timer: 20,
    timeoutNext: 'b5silent',
    choices: [
      {
        text: 'Ja: Soll ich die Abweichungen nur auflisten oder auch einschätzen, welche kritisch sind?',
        quality: 'professional',
        targets: ['w-fragen'],
        next: 'b5pro',
      },
      { text: 'Nein, alles klar. Ich mache mich sofort an die Arbeit.', quality: 'natural', next: 'b5ok' },
      { text: 'Was genau ist eine Vertragsstrafe?', quality: 'correct', next: 'b5term' },
      {
        text: 'Okay, ich checke das mal.',
        quality: 'understandable',
        feedback: '„checken“ ist im Kanzleikontext zu salopp. Besser: „Ich prüfe das.“ / „Ich sehe mir das an.“',
        next: 'b5check',
      },
    ],
  },
  {
    id: 'b5pro',
    speaker: 'kessler',
    text: 'Gute Frage. Auflisten und kurz einschätzen, was kritisch ist. Die rechtliche Bewertung übernehme ich.',
    gloss: 'Dobre pytanie. Wypisać i krótko ocenić, co jest krytyczne. Ocenę prawną biorę na siebie.',
    effects: [{ type: 'rel', npc: 'kessler', delta: 6 }, { type: 'skill', skill: 'professional', delta: 4 }, { type: 'memory', npc: 'kessler', text: 'Hat beim Briefing die richtige Rückfrage gestellt.' }],
    next: 'b6',
  },
  { id: 'b5ok', speaker: 'kessler', text: 'Gut.', gloss: 'Dobrze.', next: 'b6' },
  {
    id: 'b5term',
    speaker: 'kessler',
    text: 'Ein Betrag, den eine Partei zahlen muss, wenn sie gegen eine Pflicht aus dem Vertrag verstößt. Auf Polnisch: kara umowna. Besser jetzt fragen als heute Abend.',
    gloss: 'Kwota, którą strona musi zapłacić, jeśli naruszy obowiązek z umowy. Po polsku: kara umowna. Lepiej zapytać teraz niż wieczorem.',
    effects: [{ type: 'term', term: 'vertragsstrafe' }, { type: 'rel', npc: 'kessler', delta: 1 }],
    next: 'b6',
  },
  {
    id: 'b5check',
    speaker: 'kessler',
    text: '„Checken.“ Prüfen Sie es bitte. Gründlich.',
    gloss: '„Czeknąć”. Proszę to sprawdzić. Dokładnie.',
    effects: [{ type: 'rel', npc: 'kessler', delta: -2 }, { type: 'memory', npc: 'kessler', text: 'Hat „checken“ gesagt.' }],
    next: 'b6',
  },
  {
    id: 'b5silent',
    speaker: 'kessler',
    text: 'Keine Fragen? Gut. Dann los.',
    gloss: 'Brak pytań? Dobrze. No to do dzieła.',
    next: 'b6',
  },
  {
    id: 'b6',
    speaker: 'narrator',
    direction: 'Sie steht auf, das Gespräch ist beendet. Auf Ihrem Schreibtisch liegen zwei Stapel Papier.',
    effects: [
      { type: 'flag', flag: 'briefed' },
      { type: 'objective', mission: 'm_contract', objective: 'brief' },
      { type: 'term', term: 'vertragsstrafe' },
      { type: 'term', term: 'kuendigung' },
      { type: 'term', term: 'ruecktritt' },
      { type: 'time', set: '14:41' },
    ],
    end: true,
  },
  // ---------------------------------------------------------------- report after e-mail
  {
    id: 'rep0',
    branch: [
      { condition: { flag: 'email_good' }, next: 'rep_good' },
      { condition: { flag: 'email_ok' }, next: 'rep_ok' },
    ],
    next: 'rep_weak',
  },
  {
    id: 'rep_good',
    speaker: 'kessler',
    text: 'Ihre Mail habe ich gelesen. Klar, strukturiert – und die Sache mit Paragraf neun, Kündigung versus Rücktritt, hätte ich fast übersehen. Gute Arbeit.',
    gloss: 'Przeczytałam maila. Jasny, uporządkowany – a sprawę z § 9, wypowiedzenie kontra odstąpienie, prawie przeoczyłabym. Dobra robota.',
    effects: [{ type: 'rel', npc: 'kessler', delta: 10 }, { type: 'memory', npc: 'kessler', text: 'Erste Analyse war präzise und strukturiert.' }],
    next: 'rep_next',
  },
  {
    id: 'rep_ok',
    speaker: 'kessler',
    text: 'Inhaltlich brauchbar. Sprachlich feilen wir noch – an Mandanten schreibt man anders. Aber: gut gefunden.',
    gloss: 'Merytorycznie OK. Nad językiem jeszcze popracujemy – do klientów pisze się inaczej. Ale: dobrze znalezione.',
    effects: [{ type: 'rel', npc: 'kessler', delta: 4 }],
    next: 'rep_next',
  },
  {
    id: 'rep_weak',
    speaker: 'kessler',
    text: 'Ihre Mail war … schwer zu lesen. Erklären Sie es mir mündlich: Was ist das größte Problem?',
    gloss: 'Pana/Pani mail był… trudny do czytania. Proszę mi to wyjaśnić ustnie: jaki jest największy problem?',
    next: 'rep_weak_c',
  },
  {
    id: 'rep_weak_c',
    speaker: 'player',
    choices: [
      { text: 'Die Vertragsstrafe: 250.000 Euro in der deutschen, 25.000 Euro in der polnischen Fassung.', quality: 'professional', targets: ['uebersetzung-zahlen'], next: 'rep_weak_ok' },
      { text: 'Die Übersetzung ist schlecht.', quality: 'understandable', feedback: 'Eine Meinung ist keine Analyse. Nennen Sie Paragraf, Abweichung, Folge.', next: 'rep_weak_bad' },
    ],
  },
  { id: 'rep_weak_ok', speaker: 'kessler', text: 'Genau. Das hätte in den ersten Satz der Mail gehört.', gloss: 'Właśnie. To powinno być w pierwszym zdaniu maila.', effects: [{ type: 'rel', npc: 'kessler', delta: 2 }], next: 'rep_next' },
  {
    id: 'rep_weak_bad',
    speaker: 'kessler',
    text: 'Das ist keine Analyse, das ist eine Meinung. Paragraf sieben. Zählen Sie die Nullen.',
    gloss: 'To nie analiza, to opinia. Paragraf siódmy. Proszę policzyć zera.',
    effects: [{ type: 'rel', npc: 'kessler', delta: -3 }, { type: 'memory', npc: 'kessler', text: 'Hat die Analyse vage formuliert.' }],
    next: 'rep_next',
  },
  {
    id: 'rep_next',
    speaker: 'kessler',
    listening: true,
    skill: 'listening',
    text: 'Zwanzig Uhr, Restaurant Lindner, Prenzlauer Berg. Herr Fink wird versuchen, die Sache kleinzureden. Sie kommen mit – und wenn ich Ihnen ein Zeichen gebe, erklären Sie die Abweichungen. Auf Deutsch. Ruhig und sachlich.',
    gloss: '20:00, restauracja Lindner, Prenzlauer Berg. Pan Fink będzie próbował bagatelizować sprawę. Idzie Pan/Pani ze mną – a gdy dam znak, wyjaśni Pan/Pani rozbieżności. Po niemiecku. Spokojnie i rzeczowo.',
    next: 'rep_c',
  },
  {
    id: 'rep_c',
    speaker: 'player',
    choices: [
      { text: 'Verstanden. Ich bereite mich vor.', quality: 'natural', next: 'rep_end' },
      { text: 'Ich? Vor dem Sportdirektor?', quality: 'correct', next: 'rep_me' },
    ],
  },
  { id: 'rep_me', speaker: 'kessler', text: 'Sie. Genau Sie. Sie sind der einzige Mensch am Tisch, der beide Fassungen lesen kann.', gloss: 'Pan/Pani. Właśnie Pan/Pani. Jedyna osoba przy stole, która umie przeczytać obie wersje.', next: 'rep_end' },
  {
    id: 'rep_end',
    effects: [
      { type: 'flag', flag: 'reported' },
      { type: 'objective', mission: 'm_contract', objective: 'report' },
      { type: 'completeMission', mission: 'm_contract', outcome: 'Abweichungen dokumentiert' },
      { type: 'time', set: '19:20' },
      { type: 'message', from: 'lukas', text: 'Viel Glück heute Abend! Fink ist ein Fuchs. Lass dich nicht einwickeln 🦊' },
    ],
    end: true,
  },
]);

export const k_lukas = dlg('k_lukas', [
  { id: 'l0', branch: [{ condition: { flag: 'k_arrived', is: false }, next: '@k_reception' }], next: 'l1' },
  { id: 'l1', speaker: 'lukas', text: 'Na, alles fit? Kaffee steht in der Küche. Der gute ist der rechte.', gloss: 'No, wszystko OK? Kawa w kuchni. Ta dobra jest po prawej.', next: 'l2' },
  { id: 'l2', retrieval: { channel: 'dialogue', speaker: 'lukas' }, next: 'l3' },
  { id: 'l3', speaker: 'lukas', text: 'So, ich muss weiter – drei Schriftsätze bis morgen. Ruf, wenn was ist!', gloss: 'Dobra, lecę – trzy pisma procesowe do jutra. Wołaj, jak coś!', end: true },
]);

export const k_desk = dlg('k_desk', [
  {
    id: 'd0',
    branch: [
      { condition: { flag: 'briefed', is: false }, next: 'd_notyet' },
      { condition: { flag: 'compared', is: false }, next: 'd1' },
      { condition: { flag: 'translated', is: false }, next: 't1' },
      { condition: { flag: 'email_sent', is: false }, next: 'm1' },
    ],
    next: 'd_done',
  },
  { id: 'd_notyet', speaker: 'narrator', direction: 'Ein leerer Schreibtisch, ein Namensschild mit Ihrem Namen – falsch geschrieben. Erst zu Dr. Kessler.', end: true },
  { id: 'd_done', speaker: 'narrator', direction: 'Alles erledigt. Der Bildschirm zeigt Ihr Postfach: 14 ungelesene Mails, keine davon an Sie.', end: true },
  {
    id: 'd1',
    speaker: 'player',
    inspect: {
      instruction: 'Vergleichen Sie die deutsche und die polnische Fassung. Markieren Sie jede Zeile der polnischen Fassung, die inhaltlich von der deutschen abweicht.',
      docs: [CONTRACT_DE, CONTRACT_PL],
      correct: ['pl7', 'pl9_1', 'pl9_2'],
      explain: {
        pl7: '§ 7: Betrag um den Faktor 10 falsch – DE 250.000,00 EUR ↔ PL 25 000,00 EUR. Kritisch: Der Spieler glaubt, sein Risiko sei zehnmal kleiner.',
        pl9_1: '§ 9 Abs. 1: „außerordentliche Kündigung“ ist nicht „odstąpienie od umowy“ (= Rücktritt, wirkt auf den Vertragsschluss zurück). Richtig: „rozwiązanie umowy bez zachowania okresu wypowiedzenia z ważnej przyczyny“.',
        pl9_2: '§ 9 Abs. 2: Datum falsch – DE 30. Juni 2027 ↔ PL 30 czerwca 2026. Laut polnischer Fassung greift die Ausstiegsklausel ein Jahr zu früh.',
        pl4: '§ 4 stimmt inhaltlich überein.',
        pl10: '§ 10 stimmt: 38.500,00 EUR = 38 500,00 EUR (nur andere Zahlenschreibweise).',
        pl14: '§ 14 stimmt – und genau deshalb ist jede Abweichung gefährlich: Maßgeblich ist die deutsche Fassung.',
      },
      flagPrefix: 'found',
      targets: ['juristendeutsch', 'term-vertragsstrafe', 'term-kuendigung-ruecktritt', 'uebersetzung-zahlen'],
      next: 'd2',
    },
  },
  {
    id: 'd2',
    speaker: 'lukas',
    direction: 'Lukas lehnt sich über die Trennwand, einen Kaffeebecher in der Hand.',
    text: 'Na? Was gefunden?',
    gloss: 'No i? Znalazłeś/aś coś?',
    branch: [{ condition: { flag: 'found_pl7', is: false }, next: 'd2hint' }],
    next: 'd3',
  },
  {
    id: 'd2hint',
    speaker: 'lukas',
    text: 'Hast du dir Paragraf sieben genau angeschaut? Zähl mal die Nullen. Ich sag nur: Null.',
    gloss: 'Przyjrzałeś/aś się dokładnie paragrafowi siódmemu? Policz zera.',
    effects: [{ type: 'flag', flag: 'lukas_hint' }],
    next: 'd3',
  },
  {
    id: 'd3',
    speaker: 'player',
    input: {
      task: 'Erklären Sie Lukas locker und mündlich, was Ihnen aufgefallen ist.',
      taskGloss: 'Wyjaśnij Lukasowi luźno, ustnie, co zauważyłeś/aś.',
      mode: 'speak',
      skill: 'speaking',
      register: 'informal',
      targets: ['du-sie', 'konnektoren', 'uebersetzung-zahlen'],
      required: [
        { id: 'amount', label: 'die Vertragsstrafe / der Betrag', patterns: [String.raw`250`, String.raw`25[.\s]?000`, 'zehnmal', 'null', 'faktor', 'betrag', 'summe', 'vertragsstrafe', 'strafe'] },
        { id: 'other', label: 'eine weitere Abweichung (Datum oder Begriff)', patterns: ['2026', '2027', 'datum', 'jahr', 'ruecktritt', 'kuendigung', 'odstap', 'odstąp', 'ausstieg', '§ ?9', 'neun'] },
      ],
      bonuses: [
        { pattern: String.raw`zehnmal|faktor (zehn|10)|eine null`, dimension: 'idiomaticity', note: 'Anschaulich auf den Punkt gebracht', weight: 22 },
        { pattern: String.raw`\b(und|ausserdem|dazu kommt|und dann|plus)\b`, dimension: 'naturalness', note: 'Verknüpft', weight: 6 },
        { pattern: String.raw`krass|alter|echt|heftig|ziemlich`, dimension: 'naturalness', note: 'Passender lockerer Ton', weight: 12 },
        { pattern: String.raw`statt|anstatt|waehrend`, dimension: 'precision', note: 'Gegenüberstellung', weight: 10 },
      ],
      models: ['Ja, einiges: In der polnischen Fassung ist die Vertragsstrafe zehnmal kleiner – 25.000 statt 250.000 Euro. Und bei der Ausstiegsklausel steht 2026 statt 2027.'],
      onSuccess: 'd4s',
      onPartial: 'd4p',
      onFail: 'd4f',
    },
  },
  {
    id: 'd4s',
    speaker: 'lukas',
    text: 'Alter. Eine Null zu wenig. Das ist kein Tippfehler, das ist ein Transferdrama. Schreib das Jana, sofort.',
    gloss: 'Stary. O jedno zero za mało. To nie literówka, to dramat transferowy. Napisz to Janie, natychmiast.',
    effects: [{ type: 'rel', npc: 'lukas', delta: 5 }],
    next: 'd5',
  },
  { id: 'd4p', speaker: 'lukas', text: 'Warte – die Summe ist anders? Okay, schreib’s genau auf. Jana will Zahlen, keine Gefühle.', gloss: 'Czekaj – kwota jest inna? OK, zapisz to dokładnie. Jana chce liczb, nie uczuć.', next: 'd5' },
  { id: 'd4f', speaker: 'lukas', text: 'Hä? Sorry, ich check’s nicht. Schreib’s lieber auf, dann lese ich mit.', gloss: 'Co? Sorry, nie łapię. Lepiej to zapisz, to przeczytam.', next: 'd5' },
  {
    id: 'd5',
    effects: [{ type: 'flag', flag: 'compared' }, { type: 'objective', mission: 'm_contract', objective: 'compare' }, { type: 'time', set: '15:26' }],
    next: 't1',
  },
  // ---------------------------------------------------------------- translation PL → DE
  {
    id: 't1',
    speaker: 'narrator',
    direction: 'Eine Nachricht des Spielerberaters Paweł Mazur an Dr. Kessler – auf Polnisch. Sie leitet sie an Sie weiter: „Bitte übersetzen. Wörtlich genug für mich, sauber genug für den Verein.“',
    document: {
      kind: 'sms',
      title: 'Paweł Mazur (Berater)',
      lines: [{ text: 'Pani Mecenas, mój klient zaakceptował już polską wersję umowy. Oczekujemy, że kara umowna wyniesie 25 000 euro, tak jak ustalono. Pozdrawiam, Paweł Mazur' }],
    },
    next: 't2',
  },
  {
    id: 't2',
    speaker: 'player',
    input: {
      task: 'Übersetzen Sie die Nachricht ins Deutsche.',
      taskGloss: 'Przetłumacz wiadomość na niemiecki.',
      mode: 'translate',
      skill: 'translation',
      register: 'formal',
      source: { lang: 'pl', text: 'Pani Mecenas, mój klient zaakceptował już polską wersję umowy. Oczekujemy, że kara umowna wyniesie 25 000 euro, tak jak ustalono. Pozdrawiam, Paweł Mazur' },
      targets: ['term-vertragsstrafe', 'uebersetzung-zahlen', 'nebensatz-verbend'],
      required: [
        { id: 'accepted', label: 'hat … akzeptiert', patterns: ['akzeptiert', 'angenommen', 'zugestimmt', 'einverstanden', 'gebilligt'] },
        { id: 'version', label: 'die polnische Fassung/Version', patterns: ['polnische[n]? (fassung|version)', 'polnischen vertrag'] },
        { id: 'expect', label: 'wir erwarten / gehen davon aus', patterns: ['erwarten', 'gehen davon aus', 'gehen wir davon aus', 'rechnen damit'] },
        { id: 'agreed', label: 'wie vereinbart', patterns: ['wie vereinbart', 'wie abgesprochen', 'wie besprochen', 'vereinbarungsgemaess', 'wie festgelegt', 'wie verabredet'] },
      ],
      terms: [
        {
          term: 'kara umowna → Vertragsstrafe',
          accept: ['vertragsstrafe', 'konventionalstrafe'],
          reject: [
            { pattern: 'geldstrafe', message: '„Geldstrafe“ ist eine strafrechtliche Sanktion (PL: grzywna). Hier: „Vertragsstrafe“.' },
            { pattern: String.raw`strafe des vertrag|vertragsbusse|vertraglich\w* strafe`, message: 'Wörtlich, aber kein deutscher Rechtsbegriff. Richtig: „Vertragsstrafe“ (§§ 339 ff. BGB).' },
          ],
        },
        {
          term: 'Pani Mecenas → Anrede',
          accept: [String.raw`(sehr geehrte|liebe) frau (dr\.? )?(kessler|rechtsanwaeltin)`, String.raw`frau (dr\.? )?kessler`, 'frau rechtsanwaeltin'],
          reject: [{ pattern: String.raw`frau mecenas|frau anwalt\b|frau advokat`, message: '„Pani Mecenas“ ist eine polnische Höflichkeitsanrede. Deutsch: „Sehr geehrte Frau Dr. Kessler“ (oder „Frau Rechtsanwältin“).' }],
        },
      ],
      bonuses: [
        { pattern: String.raw`betraegt|betragen wird|in hoehe von`, dimension: 'idiomaticity', note: '„beträgt / in Höhe von“ – idiomatisch für Beträge', weight: 18 },
        { pattern: String.raw`mit freundlichen gruessen|beste gruesse|viele gruesse|freundliche gruesse`, dimension: 'style', note: 'Grußformel übertragen', weight: 10 },
        { pattern: String.raw`bereits`, dimension: 'precision', note: '„już“ → „bereits“', weight: 8 },
        { pattern: String.raw`25\.000`, dimension: 'precision', note: 'Deutsches Zahlenformat (25.000)', weight: 10 },
      ],
      models: ['Sehr geehrte Frau Dr. Kessler, mein Mandant hat die polnische Fassung des Vertrags bereits akzeptiert. Wir gehen davon aus, dass die Vertragsstrafe – wie vereinbart – 25.000 Euro beträgt. Mit freundlichen Grüßen, Paweł Mazur'],
      vocab: ['vertragsstrafe', 'fassung'],
      onSuccess: 't3s',
      onPartial: 't3p',
      onFail: 't3f',
    },
  },
  { id: 't3s', speaker: 'narrator', direction: 'Präzise. Dr. Kessler wird damit arbeiten können – und sie sieht sofort: Der Berater hat die falsche Zahl schriftlich bestätigt.', effects: [{ type: 'skill', skill: 'legal', delta: 4 }], next: 't4' },
  { id: 't3p', speaker: 'narrator', direction: 'Brauchbar – aber ein Jurist würde an Ihrer Übersetzung noch hängenbleiben. Dr. Kessler markiert zwei Stellen gelb.', next: 't4' },
  { id: 't3f', speaker: 'narrator', direction: 'Dr. Kessler antwortet mit einem einzigen Wort: „?“. Lukas übersetzt schließlich mit einem Online-Tool. Das Ergebnis ist … kreativ.', effects: [{ type: 'rel', npc: 'kessler', delta: -2 }], next: 't4' },
  // ---------------------------------------------------------------- translation DE → PL
  {
    id: 't4',
    speaker: 'kessler',
    direction: 'Chatnachricht von Dr. Kessler:',
    audio: false,
    text: 'Bitte formulieren Sie § 9 Abs. 1 korrekt auf Polnisch. Herr Wrona soll verstehen, was er unterschreibt.',
    gloss: 'Proszę poprawnie sformułować § 9 ust. 1 po polsku. Pan Wrona ma rozumieć, co podpisuje.',
    next: 't5',
  },
  {
    id: 't5',
    speaker: 'player',
    input: {
      task: 'Übersetzen Sie § 9 Abs. 1 ins Polnische.',
      taskGloss: 'Przetłumacz § 9 ust. 1 na polski – tym razem poprawnie.',
      mode: 'translate',
      skill: 'legal',
      register: 'any',
      source: { lang: 'de', text: 'Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt.' },
      targets: ['term-kuendigung-ruecktritt', 'uebersetzung-aequivalenz', 'juristendeutsch'],
      required: [
        { id: 'right', label: 'prawo (das Recht)', patterns: ['prawo', 'uprawnienie'] },
        { id: 'reason', label: 'z ważnej przyczyny (aus wichtigem Grund)', patterns: [String.raw`ważn\w* (przyczyn|powod)`, String.raw`ważnych powodów`] },
        { id: 'unaffected', label: 'pozostaje nienaruszone (bleibt unberührt)', patterns: ['nienaruszon', 'nie narusza', 'pozostaje bez zmian', 'nie wyłącza', 'nie ogranicza', 'zachowuje'] },
      ],
      terms: [
        {
          term: 'außerordentliche Kündigung',
          accept: [
            String.raw`rozwiązani\w* umowy bez (zachowania )?(okresu )?wypowiedzenia`,
            String.raw`wypowiedzeni\w* (umowy )?bez zachowania okresu wypowiedzenia`,
            String.raw`wypowiedzeni\w* (umowy )?ze skutkiem natychmiastowym`,
            String.raw`nadzwyczajn\w* wypowiedzeni`,
            String.raw`rozwiązani\w* umowy ze skutkiem natychmiastowym`,
          ],
          reject: [
            {
              pattern: 'odstąpi',
              message: '„odstąpienie od umowy“ = Rücktritt (wirkt zurück). Gemeint ist die Beendigung für die Zukunft: „rozwiązanie umowy bez zachowania okresu wypowiedzenia“.',
            },
          ],
        },
      ],
      bonuses: [
        { pattern: 'pozostaje nienaruszone', dimension: 'idiomaticity', note: 'Feststehende Formel der polnischen Vertragssprache', weight: 25 },
        { pattern: String.raw`z ważnej przyczyny`, dimension: 'idiomaticity', note: 'Kodexsprache (vgl. Art. 746 KC)', weight: 15 },
      ],
      models: ['Prawo do rozwiązania umowy bez zachowania okresu wypowiedzenia z ważnej przyczyny pozostaje nienaruszone.'],
      onSuccess: 't6s',
      onPartial: 't6p',
      onFail: 't6f',
    },
  },
  { id: 't6s', speaker: 'narrator', direction: 'Juristisch sauber. Begriff → Bedeutung → Entsprechung im polnischen Recht → Formulierung. So arbeitet eine Übersetzerin, nicht ein Wörterbuch.', effects: [{ type: 'skill', skill: 'legal', delta: 5 }], next: 't7' },
  { id: 't6p', speaker: 'narrator', direction: 'Nah dran. Aber im Recht ist „nah dran“ ein anderes Wort für „angreifbar“.', next: 't7' },
  { id: 't6f', speaker: 'narrator', direction: 'Genau der Fehler, den der Verein auch gemacht hat. Das wird Sie noch beschäftigen.', next: 't7' },
  {
    id: 't7',
    effects: [{ type: 'flag', flag: 'translated' }, { type: 'objective', mission: 'm_contract', objective: 'translate' }, { type: 'time', set: '16:18' }, { type: 'term', term: 'ausserordentliche_kuendigung' }],
    next: 'm1',
  },
  // ---------------------------------------------------------------- e-mail to Kessler
  {
    id: 'm1',
    speaker: 'narrator',
    direction: '16:18. Frist 17:00. Das Postfach ist offen.',
    next: 'm2',
  },
  {
    id: 'm2',
    speaker: 'player',
    compose: { to: 'j.kessler@kessler-aydin.de', subject: 'Vertrag Wrona – Abweichungen DE/PL' },
    input: {
      task: 'Fassen Sie für Dr. Kessler die Abweichungen zusammen und geben Sie eine kurze Empfehlung.',
      taskGloss: 'Podsumuj rozbieżności dla dr Kessler i daj krótką rekomendację. Styl: formalny e-mail.',
      mode: 'write',
      skill: 'writing',
      register: 'formal',
      minWords: 25,
      timeLimitSec: 900,
      targets: ['email-register', 'nominalstil', 'konnektoren', 'uebersetzung-zahlen', 'term-kuendigung-ruecktritt'],
      required: [
        { id: 'amount', label: 'Abweichung Vertragsstrafe (§ 7)', patterns: [String.raw`250[.\s]?000`, String.raw`25[.\s]?000`, 'faktor', 'zehnmal', String.raw`vertragsstrafe[^.]*(abweich|falsch|niedrig|gering|anders)`] },
        { id: 'date', label: 'Abweichung Datum (§ 9 Abs. 2)', patterns: ['2026', '2027', String.raw`datum`, String.raw`ausstiegsklausel[^.]*(frueher|jahr)`] },
        { id: 'term', label: 'Begriffsfehler Kündigung/Rücktritt (§ 9 Abs. 1)', patterns: ['ruecktritt', 'odstap', 'odstąp', String.raw`kuendigung[^.]*(falsch|uebersetzt|wiedergegeben)`, String.raw`§ ?9 abs\.? ?1`, String.raw`9 \(1\)`] },
        { id: 'reco', label: 'Empfehlung', patterns: ['empfehle', 'empfehlung', 'schlage vor', 'vorschlag', String.raw`sollte[n]? [^.]*(korrigier|berichtig|anpass|neu)`, 'korrigier', 'berichtig', 'vor (der )?unterzeichnung', 'nicht unterschreiben', 'zusatzvereinbarung', 'nachtrag'] },
      ],
      errors: [
        {
          pattern: String.raw`^(hallo|hi|hey) (jana|frau)`,
          target: 'email-register',
          category: 'register',
          severity: 2,
          message: 'Erste E-Mail an die Partnerin: „Sehr geehrte Frau Dr. Kessler,“ oder „Liebe Frau Kessler,“ – nicht „Hallo“.',
        },
        { pattern: String.raw`\blg\b|\bvg\b|\bmfg\b`, target: 'email-register', category: 'professional', severity: 1, message: 'Abkürzungen wie „LG/MfG“ wirken in der Kanzlei nachlässig. Ausschreiben: „Mit freundlichen Grüßen“.' },
      ],
      bonuses: [
        { pattern: String.raw`(sehr geehrte|liebe) frau (dr\.? )?kessler`, dimension: 'register', note: 'Korrekte Anrede', weight: 12 },
        { pattern: String.raw`(mit freundlichen|beste|viele) gruess`, dimension: 'style', note: 'Grußformel', weight: 10 },
        { pattern: String.raw`abweichung`, dimension: 'precision', note: '„Abweichung“ – präziser Fachbegriff', weight: 12 },
        { pattern: String.raw`massgeblich|verbindlich`, dimension: 'register', note: 'Hinweis auf die maßgebliche Fassung', weight: 10 },
        { pattern: String.raw`erstens|zweitens|zunaechst|darueber hinaus|zudem|ausserdem|schliesslich|1\.|2\.`, dimension: 'style', note: 'Klare Struktur', weight: 15 },
        { pattern: String.raw`(vor|nach) (der )?unterzeichnung|bei unterzeichnung`, dimension: 'idiomaticity', note: 'Nominalstil (vor Unterzeichnung)', weight: 15 },
        { pattern: String.raw`§ ?7|§ ?9`, dimension: 'precision', note: 'Paragraphen genannt', weight: 10 },
        { pattern: String.raw`odstąpienie|rücktritt|ruecktritt`, dimension: 'precision', note: 'Begriffsfehler benannt', weight: 8 },
      ],
      models: [
        'Sehr geehrte Frau Dr. Kessler,\n\nbeim Abgleich der beiden Fassungen habe ich drei Abweichungen festgestellt:\n\n1. § 7 (Vertragsstrafe): DE 250.000,00 EUR, PL 25.000,00 EUR – Abweichung um den Faktor 10.\n2. § 9 Abs. 1: Die „außerordentliche Kündigung“ wurde mit „odstąpienie od umowy“ (= Rücktritt) übersetzt.\n3. § 9 Abs. 2 (Ausstiegsklausel): DE 30.06.2027, PL 30.06.2026.\n\nDa ausschließlich die deutsche Fassung maßgeblich ist, empfehle ich, die polnische Fassung vor der Unterzeichnung zu berichtigen oder die Punkte in einer Zusatzvereinbarung klarzustellen.\n\nMit freundlichen Grüßen\n{first} {last}',
      ],
      vocab: ['abweichung', 'fassung', 'massgeblich', 'unterzeichnung'],
      onSuccess: 'm3s',
      onPartial: 'm3p',
      onFail: 'm3f',
    },
  },
  { id: 'm3s', speaker: 'narrator', direction: 'Gesendet: 16:47. Zwei Minuten später: „Gelesen.“', effects: [{ type: 'flag', flag: 'email_sent' }, { type: 'flag', flag: 'email_good' }], next: 'm4' },
  { id: 'm3p', speaker: 'narrator', direction: 'Gesendet: 16:52. Keine Antwort. Dr. Kessler liest offenbar zweimal.', effects: [{ type: 'flag', flag: 'email_sent' }, { type: 'flag', flag: 'email_ok' }], next: 'm4' },
  { id: 'm3f', speaker: 'narrator', direction: 'Gesendet: 16:59. Eine Minute vor der Frist. Und Sie ahnen: Das war nicht Ihre beste Mail.', effects: [{ type: 'flag', flag: 'email_sent' }, { type: 'flag', flag: 'email_weak' }], next: 'm4' },
  {
    id: 'm4',
    speaker: 'narrator',
    direction: 'Dr. Kessler erwartet Sie im Besprechungsraum.',
    effects: [{ type: 'objective', mission: 'm_contract', objective: 'email' }, { type: 'time', set: '17:05' }],
    end: true,
  },
]);
