import { dlg } from '../../dsl';

/** MISSION: DER SCHLÜSSEL — Graefestraße 12 · and Kreuzberg ambience */

export const kb_arrive = dlg('kb_arrive', [
  {
    id: 'a1',
    speaker: 'narrator',
    direction: 'Graefestraße. Fünfstöckige Altbauten, Stuck, Graffiti bis zum ersten Stock. Vor der Nummer 12 wartet eine Frau mit grauem Bob und Aktenmappe. Sie sieht auf die Uhr.',
    effects: [{ type: 'flag', flag: 'kb_arrived' }, { type: 'objective', mission: 'm_key', objective: 'meet' }],
    end: true,
  },
]);

export const key_main = dlg('key_main', [
  {
    id: 'k0',
    branch: [
      { condition: { all: [{ flag: 'late' }, { flag: 'late_informed', is: false }] }, next: 'k1late' },
      { condition: { flag: 'late' }, next: 'k1late_ok' },
    ],
    next: 'k1',
  },
  {
    id: 'k1',
    speaker: 'wiesner',
    text: 'Guten Morgen. Sie müssen {g:der neue Mieter|die neue Mieterin|die neue Mietpartei} sein. Pünktlich – das gefällt mir.',
    gloss: 'Dzień dobry. Pan/Pani musi być nowym najemcą. Punktualnie – to mi się podoba.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: 4 }],
    next: 'k2',
  },
  {
    id: 'k1late',
    speaker: 'wiesner',
    text: 'Sie sind spät dran. Ich hatte Sie um Viertel nach acht erwartet – und keine Nachricht. Ich habe um halb zehn den nächsten Termin.',
    gloss: 'Spóźnił się Pan / spóźniła się Pani. Czekałam o 8:15 – i żadnej wiadomości.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: -5 }, { type: 'memory', npc: 'wiesner', text: 'Kam am ersten Tag zu spät – ohne Nachricht.' }],
    next: 'k2',
  },
  {
    id: 'k1late_ok',
    speaker: 'wiesner',
    text: 'Da sind Sie ja. Die falsche S-Bahn, hm? Das passiert hier jedem einmal. Einmal.',
    gloss: 'No jest Pan/Pani. Zła kolejka, co? To się każdemu zdarza raz. Raz.',
    effects: [{ type: 'memory', npc: 'wiesner', text: 'Kam zu spät, hat aber vorher Bescheid gegeben.' }],
    next: 'k2',
  },
  {
    id: 'k2',
    speaker: 'player',
    input: {
      task: 'Stellen Sie sich Frau Wiesner vor: Name, woher Sie kommen und was Sie in Berlin machen.',
      taskGloss: 'Przedstaw się: imię i nazwisko, skąd jesteś, co będziesz robić w Berlinie.',
      mode: 'speak',
      skill: 'speaking',
      register: 'formal',
      targets: ['du-sie', 'v2-inversion', 'trennbare-verben'],
      required: [
        { id: 'name', label: 'Ihr Name', patterns: ['ich bin', 'ich heisse', 'mein name', '{first}', '{last}'] },
        { id: 'origin', label: 'woher Sie kommen', patterns: ['polen', 'polnisch', 'krakau', 'warschau', 'posen', 'breslau', 'danzig', 'lodz', 'stettin', 'kattowitz', 'komme aus', 'aus \\w+'] },
        { id: 'job', label: 'was Sie in Berlin machen', patterns: ['arbeit', 'job', 'stelle', 'kanzlei', 'anfang', 'fange', 'beginne', 'jurist', 'anwalt', 'uebersetz', 'firma', 'studier'] },
      ],
      bonuses: [
        { pattern: '(guten morgen|guten tag),? frau wiesner', dimension: 'register', note: 'Mit Namen begrüßt', weight: 10 },
        { pattern: 'freut mich|es freut mich|schoen, sie kennenzulernen', dimension: 'naturalness', note: 'Natürliche Begrüßungsformel', weight: 20 },
        { pattern: String.raw`ich fange [^.]*\ban\b|ab montag|naechste woche`, dimension: 'idiomaticity', note: 'Trennbares Verb / Zeitangabe korrekt eingesetzt', weight: 20 },
        { pattern: 'in einer kanzlei|bei einer kanzlei', dimension: 'precision', note: 'Präzise Angabe', weight: 10 },
      ],
      models: [
        'Guten Morgen, Frau Wiesner! Ich bin {first} {last} und komme aus Polen. Ich fange nächste Woche in einer Kanzlei in Mitte an. Freut mich sehr, Sie kennenzulernen.',
      ],
      vocab: ['anfangen', 'kanzlei'],
      onSuccess: 'k3s',
      onPartial: 'k3p',
      onFail: 'k3f',
    },
  },
  {
    id: 'k3s',
    speaker: 'wiesner',
    text: 'Freut mich ebenfalls. Eine Kanzlei, soso. Dann wissen Sie ja, wie wichtig Regeln sind. Kommen Sie.',
    gloss: 'Mnie również miło. Kancelaria, no proszę. To wie Pan/Pani, jak ważne są zasady. Proszę za mną.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: 6 }, { type: 'objective', mission: 'm_key', objective: 'meet' }],
    next: 'k4',
  },
  {
    id: 'k3p',
    speaker: 'wiesner',
    text: 'Aha. Schön. Kommen Sie, ich zeige Ihnen alles.',
    gloss: 'Aha. Dobrze. Proszę, pokażę wszystko.',
    effects: [{ type: 'objective', mission: 'm_key', objective: 'meet' }],
    next: 'k4',
  },
  {
    id: 'k3f',
    speaker: 'wiesner',
    rate: 0.85,
    text: 'Entschuldigung – wie war Ihr Name? … Gut. Kommen Sie, ich zeige Ihnen die Wohnung.',
    gloss: 'Przepraszam – jak się Pan/Pani nazywa? … Dobrze. Pokażę mieszkanie.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: -2 }, { type: 'objective', mission: 'm_key', objective: 'meet' }],
    next: 'k4',
  },
  {
    id: 'k4',
    speaker: 'wiesner',
    direction: 'Treppenhaus, dritter Stock links. Die Tür knarrt. Frau Wiesner bleibt im Flur stehen und spricht, ohne Luft zu holen.',
    listening: true,
    skill: 'listening',
    text: 'Also, die Hausordnung. Der Müll wird getrennt: Verpackungen in die gelbe Tonne, Papier in die blaue, Bioabfall in die braune. Glas bringen Sie bitte zum Container an der Ecke – aber nicht nach zwanzig Uhr. Ruhezeiten sind von zweiundzwanzig bis sechs Uhr und sonntags den ganzen Tag. Und die Kaution – drei Monatsmieten, also zweitausenddreihundertsiebzig Euro – überweisen Sie bitte bis Freitag.',
    gloss: 'Regulamin: śmieci segregujemy – opakowania do żółtego pojemnika, papier do niebieskiego, bio do brązowego. Szkło do kontenera na rogu, ale nie po 20:00. Cisza nocna 22–6 i w niedziele cały dzień. Kaucję – trzy czynsze, 2370 euro – proszę przelać do piątku.',
    effects: [{ type: 'objective', mission: 'm_key', objective: 'rules' }],
    next: 'k5',
  },
  {
    id: 'k5',
    speaker: 'player',
    choices: [
      { text: 'Könnten Sie das bitte noch einmal etwas langsamer wiederholen?', quality: 'natural', targets: ['hoeflichkeit-k2'], next: 'k4slow', effects: [{ type: 'rel', npc: 'wiesner', delta: 1 }] },
      { text: 'Alles klar, verstanden.', quality: 'correct', next: 'k6' },
      { text: 'Was? Zu schnell!', quality: 'understandable', targets: ['hoeflichkeit-k2'], feedback: 'Verständlich, aber schroff. „Könnten Sie das bitte langsamer wiederholen?“ öffnet mehr Türen.', next: 'k4slow', effects: [{ type: 'rel', npc: 'wiesner', delta: -2 }] },
    ],
  },
  {
    id: 'k4slow',
    speaker: 'wiesner',
    rate: 0.78,
    listening: true,
    skill: 'listening',
    text: 'Verpackungen: gelbe Tonne. Papier: blaue Tonne. Bioabfall: braune Tonne. Glas: Container an der Ecke, nicht nach zwanzig Uhr. Ruhe von zweiundzwanzig bis sechs Uhr und am Sonntag. Kaution: zweitausenddreihundertsiebzig Euro, bis Freitag.',
    gloss: 'Opakowania – żółty. Papier – niebieski. Bio – brązowy. Szkło – kontener, nie po 20. Cisza 22–6 i w niedzielę. Kaucja 2370 euro do piątku.',
    next: 'k6',
  },
  {
    id: 'k6',
    speaker: 'wiesner',
    text: 'Gut. Dann eine Frage, damit ich sicher bin: Wohin gehört ein leerer Joghurtbecher?',
    gloss: 'Dobrze. Pytanie kontrolne: gdzie wyrzuca się pusty kubek po jogurcie?',
    next: 'k6c',
  },
  {
    id: 'k6c',
    speaker: 'player',
    choices: [
      { text: 'In die gelbe Tonne.', quality: 'natural', targets: ['wechselpraep', 'adj-endungen'], next: 'k7ok' },
      {
        text: 'In der gelben Tonne.',
        quality: 'understandable',
        targets: ['wechselpraep'],
        feedback: 'Wohin? → Akkusativ: in die gelbe Tonne. (Wo? → in der gelben Tonne.)',
        next: 'k7meh',
      },
      { text: 'In die blaue Tonne.', quality: 'incorrect', feedback: 'Blau = Papier. Der Becher ist eine Verpackung → gelbe Tonne.', next: 'k7wrong' },
    ],
  },
  { id: 'k7ok', speaker: 'wiesner', text: 'Sehr gut. Sie haben aufgepasst.', gloss: 'Bardzo dobrze. Uważał Pan / uważała Pani.', effects: [{ type: 'rel', npc: 'wiesner', delta: 4 }], next: 'k8' },
  { id: 'k7meh', speaker: 'wiesner', text: 'Gelbe Tonne, genau. In die gelbe Tonne.', gloss: 'Żółty, zgadza się.', effects: [{ type: 'rel', npc: 'wiesner', delta: 1 }], next: 'k8' },
  {
    id: 'k7wrong',
    speaker: 'wiesner',
    text: 'Nein, nein. Blau ist Papier. Der Becher kommt in die gelbe Tonne. Das ist wichtig hier im Haus.',
    gloss: 'Nie, nie. Niebieski to papier. Kubek do żółtego. To w tym domu ważne.',
    effects: [{ type: 'rel', npc: 'wiesner', delta: -2 }, { type: 'flag', flag: 'trash_confused' }, { type: 'memory', npc: 'wiesner', text: 'Hat die Mülltrennung verwechselt.' }],
    next: 'k8',
  },
  { id: 'k8', speaker: 'wiesner', text: 'Und bis wann überweisen Sie die Kaution?', gloss: 'A do kiedy przeleje Pan/Pani kaucję?', next: 'k8c' },
  {
    id: 'k8c',
    speaker: 'player',
    choices: [
      { text: 'Bis Freitag.', quality: 'natural', next: 'k9', effects: [{ type: 'skill', skill: 'listening', delta: 3 }] },
      { text: 'Bis Ende des Monats.', quality: 'incorrect', feedback: 'Frau Wiesner hat „bis Freitag“ gesagt.', next: 'k8wrong', effects: [{ type: 'skill', skill: 'listening', delta: -3 }] },
      { text: 'Bis Sonntag.', quality: 'incorrect', feedback: 'Sonntag war die Ruhezeit. Die Kaution: bis Freitag.', next: 'k8wrong', effects: [{ type: 'skill', skill: 'listening', delta: -3 }] },
    ],
  },
  { id: 'k8wrong', speaker: 'wiesner', text: 'Bis Freitag, hatte ich gesagt. Freitag.', gloss: 'Do piątku, mówiłam.', effects: [{ type: 'rel', npc: 'wiesner', delta: -1 }], next: 'k9' },
  {
    id: 'k9',
    speaker: 'wiesner',
    direction: 'Frau Wiesner legt zwei Schlüssel auf die Fensterbank und greift nach ihrer Aktenmappe.',
    text: 'So. Haustür und Wohnung. Haben Sie noch Fragen?',
    gloss: 'Tak. Drzwi wejściowe i mieszkanie. Ma Pan/Pani jeszcze pytania?',
    next: 'k9c',
  },
  {
    id: 'k9c',
    speaker: 'player',
    choices: [
      {
        text: 'Ja, eine noch: Könnten Sie mir bitte die Wohnungsgeberbestätigung ausstellen? Die brauche ich für die Anmeldung.',
        quality: 'professional',
        targets: ['hoeflichkeit-k2'],
        next: 'k10good',
      },
      {
        text: 'Geben Sie mir noch die Bestätigung für das Amt.',
        quality: 'understandable',
        targets: ['hoeflichkeit-k2'],
        feedback: 'Ein Imperativ ohne „bitte“ wirkt fordernd. Besser: „Könnten Sie mir bitte … geben?“',
        next: 'k10rude',
      },
      { text: 'Ich brauche noch … ein Papier … für die Anmeldung? Wie heißt das?', quality: 'understandable', next: 'k10help' },
      { text: 'Nein, danke. Auf Wiedersehen!', quality: 'correct', next: 'k10none' },
    ],
  },
  {
    id: 'k10good',
    speaker: 'wiesner',
    text: 'Selbstverständlich. Die habe ich schon vorbereitet. Sie sind gut informiert.',
    gloss: 'Oczywiście. Już przygotowałam. Jest Pan/Pani dobrze poinformowany/a.',
    effects: [{ type: 'item', item: 'wgb' }, { type: 'rel', npc: 'wiesner', delta: 5 }, { type: 'memory', npc: 'wiesner', text: 'Hat höflich und korrekt nach der Wohnungsgeberbestätigung gefragt.' }],
    next: 'k11',
  },
  {
    id: 'k10rude',
    speaker: 'wiesner',
    text: '… Bitte. Hier.',
    gloss: '… Proszę. Tutaj.',
    effects: [{ type: 'item', item: 'wgb' }, { type: 'rel', npc: 'wiesner', delta: -3 }],
    next: 'k11',
  },
  {
    id: 'k10help',
    speaker: 'wiesner',
    text: 'Sie meinen die Wohnungsgeberbestätigung. Woh-nungs-ge-ber-be-stä-ti-gung. Hier, bitte.',
    gloss: 'Chodzi o zaświadczenie od wynajmującego (Wohnungsgeberbestätigung). Proszę.',
    effects: [{ type: 'item', item: 'wgb' }, { type: 'rel', npc: 'wiesner', delta: 2 }, { type: 'vocab', words: ['wohnungsgeberbestaetigung'], mode: 'seen' }],
    next: 'k11',
  },
  {
    id: 'k10none',
    speaker: 'wiesner',
    text: 'Auf Wiedersehen. Und denken Sie an die Mülltrennung!',
    gloss: 'Do widzenia. I proszę pamiętać o segregacji śmieci!',
    effects: [{ type: 'flag', flag: 'no_wgb' }],
    next: 'k11',
  },
  {
    id: 'k11',
    speaker: 'narrator',
    direction: 'Die Tür fällt ins Schloss. Zwei Schlüssel, zwei Zimmer, Dielen, die bei jedem Schritt etwas sagen. Ihr Magen sagt auch etwas.',
    effects: [
      { type: 'item', item: 'keys' },
      { type: 'flag', flag: 'key_done' },
      { type: 'objective', mission: 'm_key', objective: 'keys' },
      { type: 'completeMission', mission: 'm_key', outcome: 'Schlüssel übernommen' },
      { type: 'time', set: '09:24' },
      { type: 'message', from: 'kasia', text: 'Und? Hast du die Schlüssel? 🔑 Geh ins Café Kiezbohne an der Ecke – Emre macht den besten Cappuccino im Kiez. ☕' },
      { type: 'moveTo', location: 'kreuzberg' },
    ],
    end: true,
  },
]);

export const kb_spaeti = dlg('kb_spaeti', [
  {
    id: 's1',
    speaker: 'narrator',
    direction: 'Späti „Graefe 24/7“. Club-Mate, Zeitungen, Pfandflaschen. Auf einem handgeschriebenen Schild steht:',
    document: {
      kind: 'sign',
      title: 'SPÄTI',
      lines: [
        { text: 'Kein Kartenzahlung!!' , highlight: true, id: 'err' },
        { text: 'Pfandrückgabe nur bis 22 Uhr' },
        { text: 'Toilette nur für Kunden' },
      ],
    },
    next: 's2',
  },
  {
    id: 's2',
    speaker: 'player',
    direction: 'Das Schild hat einen Fehler. Wie müsste es richtig heißen?',
    choices: [
      { text: 'Keine Kartenzahlung!', quality: 'natural', targets: ['genus'], next: 's3ok' },
      { text: 'Kein Kartenzahlung! (ist korrekt)', quality: 'incorrect', targets: ['genus'], feedback: 'die Zahlung → feminin → „keine Kartenzahlung“.', next: 's3' },
    ],
  },
  { id: 's3ok', speaker: 'narrator', direction: 'Richtig: die Zahlung → keine Kartenzahlung. Berlin schreibt, wie es spricht.', end: true },
  { id: 's3', speaker: 'narrator', direction: 'die Zahlung (feminin) → keine Kartenzahlung.', end: true },
]);
