import type { Location } from '../../engine/types';

const active = (mission: string) => ({ mission, status: 'active' as const });
const done = (mission: string) => ({ mission, status: 'completed' as const });

export const LOCATIONS: Location[] = [
  {
    id: 'hbf',
    city: 'berlin',
    name: 'Hauptbahnhof',
    district: 'Moabit · Mitte',
    art: 'hauptbahnhof',
    ambience: 'station',
    description: 'Glas, Stahl, fünf Ebenen. Züge über und unter Ihnen. Es riecht nach Kaffee und Bremsstaub.',
    map: { x: 432, y: 300 },
    transit: 'S3 · S5 · S7 · S9 · U5 · Regional- und Fernverkehr',
    startsUnlocked: true,
    onEnter: [{ id: 'hbf_intro', condition: { flag: 'intro_done', is: false }, dialogue: 'hbf_intro' }],
    hotspots: [
      { id: 'board', label: 'Abfahrtstafel lesen', x: 30, y: 30, kind: 'inspect', dialogue: 'hbf_board' },
      { id: 'info', label: 'DB Information', x: 73, y: 60, kind: 'talk', npc: 'pohl', dialogue: 'hbf_pohl' },
      {
        id: 'platforms',
        label: 'Zu den Gleisen',
        x: 50,
        y: 72,
        kind: 'use',
        dialogue: 'hbf_platforms',
        condition: active('m_platform'),
      },
    ],
  },
  {
    id: 'kreuzberg',
    city: 'berlin',
    name: 'Graefekiez',
    district: 'Kreuzberg',
    art: 'street',
    ambience: 'street',
    description: 'Altbauten, Kastanien, Fahrräder an jedem Laternenpfahl. Der Kiez wacht gerade auf.',
    map: { x: 608, y: 452 },
    transit: 'U1 · U3 · U8 Kottbusser Tor · U7 Schönleinstraße',
    onEnter: [{ id: 'kb_arrive', condition: { all: [active('m_key'), { flag: 'kb_arrived', is: false }] }, dialogue: 'kb_arrive' }],
    hotspots: [
      { id: 'cafe', label: 'Café Kiezbohne', x: 20, y: 62, kind: 'exit', effects: [{ type: 'moveTo', location: 'cafe' }], condition: { flag: 'key_done' } },
      { id: 'house', label: 'Graefestraße 12', x: 52, y: 58, kind: 'talk', npc: 'wiesner', dialogue: 'key_main', condition: active('m_key') },
      { id: 'home', label: 'Nach oben in die Wohnung', x: 52, y: 58, kind: 'exit', effects: [{ type: 'moveTo', location: 'wohnung' }], condition: { flag: 'key_done' } },
      { id: 'spaeti', label: 'Späti', x: 79, y: 64, kind: 'inspect', dialogue: 'kb_spaeti' },
    ],
  },
  {
    id: 'wohnung',
    city: 'berlin',
    name: 'Ihre Wohnung',
    district: 'Kreuzberg · Graefestraße 12, 3. OG links',
    art: 'apartment',
    ambience: 'apartment',
    description: 'Zwei Zimmer, Dielenboden, Kachelofen, der nicht mehr funktioniert. Ihr erstes Zuhause in Deutschland.',
    map: { x: 608, y: 452 },
    parent: 'kreuzberg',
    hotspots: [
      { id: 'desk', label: 'Schreibtisch · Training', x: 22, y: 64, kind: 'use', dialogue: 'home_desk' },
      { id: 'window', label: 'Aus dem Fenster sehen', x: 55, y: 38, kind: 'inspect', dialogue: 'home_window' },
      { id: 'bed', label: 'Schlafen', x: 81, y: 70, kind: 'use', dialogue: 'home_bed' },
      { id: 'door', label: 'Auf die Straße', x: 7, y: 58, kind: 'exit', effects: [{ type: 'moveTo', location: 'kreuzberg' }] },
    ],
  },
  {
    id: 'cafe',
    city: 'berlin',
    name: 'Café Kiezbohne',
    district: 'Kreuzberg · Graefestraße',
    art: 'cafe',
    ambience: 'cafe',
    description: 'Eine Siebträgermaschine zischt. Jemand diskutiert über Mieten. Es riecht nach Kardamom.',
    map: { x: 608, y: 452 },
    parent: 'kreuzberg',
    onEnter: [{ id: 'cafe_first', condition: { all: [active('m_cafe'), { flag: 'cafe_ordered', is: false }] }, dialogue: 'cafe_order' }],
    hotspots: [
      { id: 'emre', label: 'Mit Emre sprechen', x: 63, y: 58, kind: 'talk', npc: 'emre', dialogue: 'cafe_emre' },
      { id: 'window', label: 'Am Fenster sitzen', x: 20, y: 64, kind: 'inspect', dialogue: 'cafe_window' },
      { id: 'exit', label: 'Hinaus in den Kiez', x: 6, y: 60, kind: 'exit', effects: [{ type: 'moveTo', location: 'kreuzberg' }] },
    ],
  },
  {
    id: 'kanzlei',
    city: 'berlin',
    name: 'Kessler & Aydın',
    district: 'Mitte · Friedrichstraße 148, 4. OG',
    art: 'office',
    ambience: 'office',
    description: 'Glaswände, Aktenordner, ein Blick auf die Friedrichstraße. Hier wird schnell gesprochen.',
    map: { x: 500, y: 334 },
    transit: 'U6 · S-Bahn Friedrichstraße',
    onEnter: [{ id: 'k_arrive', condition: { all: [active('m_contract'), { flag: 'k_arrived', is: false }] }, dialogue: 'k_reception' }],
    hotspots: [
      { id: 'lukas', label: 'Lukas', x: 18, y: 60, kind: 'talk', npc: 'lukas', dialogue: 'k_lukas' },
      { id: 'meeting', label: 'Besprechungsraum', x: 52, y: 48, kind: 'talk', npc: 'kessler', dialogue: 'k_kessler' },
      { id: 'desk', label: 'Ihr Schreibtisch', x: 80, y: 64, kind: 'use', dialogue: 'k_desk' },
    ],
  },
  {
    id: 'restaurant',
    city: 'berlin',
    name: 'Restaurant Lindner',
    district: 'Prenzlauer Berg · Kollwitzkiez',
    art: 'restaurant',
    ambience: 'restaurant',
    description: 'Kerzen, dunkles Holz, leise Gespräche. Ein Tisch für drei ist reserviert. Einer wartet schon.',
    map: { x: 574, y: 232 },
    transit: 'U2 Senefelderplatz',
    onEnter: [{ id: 'dinner', condition: { all: [active('m_dinner'), { flag: 'dinner_started', is: false }] }, dialogue: 'dinner_main' }],
    hotspots: [{ id: 'table', label: 'Zum Tisch', x: 50, y: 62, kind: 'talk', npc: 'fink', dialogue: 'dinner_table' }],
  },
  {
    id: 'spree',
    city: 'berlin',
    name: 'Kastanienallee, nachts',
    district: 'Prenzlauer Berg',
    art: 'spree',
    ambience: 'rain',
    description: 'Regen auf Kopfsteinpflaster. Die Tram quietscht in der Kurve. Ihr Telefon vibriert.',
    map: { x: 560, y: 250 },
    parent: 'restaurant',
    hotspots: [{ id: 'home', label: 'Nach Hause fahren', x: 50, y: 72, kind: 'exit', dialogue: 'night_home', condition: { flag: 'night_call_done' } }],
  },
  {
    id: 'amt',
    city: 'berlin',
    name: 'Bürgeramt',
    district: 'Friedrichshain-Kreuzberg',
    art: 'buergeramt',
    ambience: 'office',
    description: 'Wartenummern, Neonlicht, ein Gummibaum. Die Anzeige springt auf B-217.',
    map: { x: 690, y: 380 },
    transit: 'U1 · U3 Warschauer Straße',
    hotspots: [
      { id: 'counter', label: 'Schalter 4', x: 64, y: 58, kind: 'talk', npc: 'amt', dialogue: 'amt_main', condition: active('m_amt') },
      { id: 'display', label: 'Aufrufanzeige', x: 30, y: 28, kind: 'inspect', dialogue: 'amt_display' },
    ],
  },
  {
    id: 'stadion',
    city: 'berlin',
    name: 'Stadion An der Spree',
    district: 'Köpenick',
    art: 'stadium',
    ambience: 'street',
    description: 'Heimat des FC Spree Berlin 1911.',
    map: { x: 858, y: 560 },
    locked: 'TAG 3 · MATCHDAY',
    hotspots: [],
  },
  {
    id: 'hotel',
    city: 'berlin',
    name: 'Hotel Hansa',
    district: 'Charlottenburg',
    art: 'hotel',
    ambience: 'office',
    description: 'Wo Spielerberater absteigen.',
    map: { x: 250, y: 350 },
    locked: 'TAG 2 · 48 STUNDEN',
    hotspots: [],
  },
];

export const LOCATION_BY_ID: Record<string, Location> = Object.fromEntries(LOCATIONS.map((l) => [l.id, l]));

export { active, done };
