import type { Mission } from '../../engine/types';

export const MISSIONS: Mission[] = [
  {
    id: 'm_platform',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'DAS FALSCHE GLEIS',
    title: 'Das falsche Gleis',
    titleEn: 'The Wrong Platform',
    time: '06:42',
    synopsis: 'Ankunft am Hauptbahnhof. Kasia hat Ihnen den Weg nach Kreuzberg geschickt. Die Bahn hat andere Pläne.',
    objectives: [
      { id: 'read_sms', text: 'Lesen Sie Kasias Nachricht', location: 'hbf' },
      { id: 'find_s5', text: 'Finden Sie die S5 Richtung Strausberg', location: 'hbf' },
      { id: 'board', text: 'Steigen Sie in die richtige S-Bahn', location: 'hbf' },
    ],
    targets: ['w-fragen', 'dativ-praep', 'hoeflichkeit-k2', 'du-sie', 'nebensatz-verbend'],
    xp: 120,
    rewards: [{ type: 'unlockLocation', location: 'kreuzberg' }, { type: 'startMission', mission: 'm_key' }],
  },
  {
    id: 'm_key',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'DER SCHLÜSSEL',
    title: 'Der Schlüssel',
    titleEn: 'The Key',
    time: '08:15',
    synopsis: 'Frau Wiesner übergibt die Wohnung. Sie erklärt die Hausordnung – schnell. Und ohne eine bestimmte Bescheinigung gibt es keine Anmeldung.',
    objectives: [
      { id: 'meet', text: 'Treffen Sie Frau Wiesner in der Graefestraße 12', location: 'kreuzberg' },
      { id: 'rules', text: 'Verstehen Sie die Hausordnung', location: 'kreuzberg' },
      { id: 'keys', text: 'Übernehmen Sie die Schlüssel', location: 'kreuzberg' },
    ],
    targets: ['du-sie', 'wechselpraep', 'hoeflichkeit-k2', 'perfekt-sein', 'v2-inversion'],
    xp: 140,
    rewards: [{ type: 'startMission', mission: 'm_cafe' }],
  },
  {
    id: 'm_cafe',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'ERSTER KAFFEE',
    title: 'Erster Kaffee',
    titleEn: 'First Coffee',
    time: '09:40',
    synopsis: 'Seit fünf Uhr unterwegs. Das Café an der Ecke hat geöffnet. Kaffee bestellen klingt einfach. Ist es auch – bis das Kartenlesegerät streikt.',
    objectives: [
      { id: 'enter', text: 'Gehen Sie ins Café Kiezbohne', location: 'kreuzberg' },
      { id: 'order', text: 'Bestellen Sie Frühstück', location: 'cafe' },
    ],
    targets: ['hoeflichkeit-k2', 'adj-endungen', 'du-sie', 'perfekt-sein'],
    xp: 100,
  },
  {
    id: 'm_call',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'DER ANRUF',
    title: 'Der Anruf',
    titleEn: 'The Call',
    time: '10:52',
    synopsis: 'Unbekannte Nummer. +49 30 … Eine Stimme, die keine Zeit hat.',
    objectives: [
      { id: 'answer', text: 'Nehmen Sie den Anruf an', location: 'cafe' },
      { id: 'confirm', text: 'Bestätigen Sie Termin und Adresse', location: 'cafe' },
    ],
    targets: ['uhrzeit', 'passiv', 'hoeflichkeit-k2'],
    xp: 110,
    rewards: [{ type: 'unlockLocation', location: 'kanzlei' }, { type: 'startMission', mission: 'm_contract' }],
  },
  {
    id: 'm_contract',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'DER VERTRAG',
    title: 'Der Vertrag',
    titleEn: 'The Contract',
    time: '14:30',
    synopsis: 'Ein polnischer Innenverteidiger soll heute Abend beim FC Spree unterschreiben. Die polnische Fassung seines Vertrags stimmt nicht mit der deutschen überein. Niemand außer Ihnen kann beide lesen.',
    objectives: [
      { id: 'arrive', text: 'Melden Sie sich in der Kanzlei (Friedrichstraße 148)', location: 'kanzlei' },
      { id: 'brief', text: 'Briefing bei Dr. Kessler', location: 'kanzlei' },
      { id: 'compare', text: 'Vergleichen Sie beide Fassungen (Ihr Schreibtisch)', location: 'kanzlei' },
      { id: 'translate', text: 'Übersetzen Sie die Nachricht des Beraters und § 9 Abs. 1', location: 'kanzlei' },
      { id: 'email', text: 'Schicken Sie Dr. Kessler bis 17:00 eine Zusammenfassung', location: 'kanzlei' },
      { id: 'report', text: 'Besprechen Sie Ihr Ergebnis mit Dr. Kessler', location: 'kanzlei' },
    ],
    targets: ['term-vertragsstrafe', 'term-kuendigung-ruecktritt', 'uebersetzung-zahlen', 'email-register', 'nominalstil', 'du-sie', 'juristendeutsch'],
    xp: 320,
    boss: true,
    rewards: [{ type: 'unlockLocation', location: 'restaurant' }, { type: 'startMission', mission: 'm_dinner' }],
  },
  {
    id: 'm_dinner',
    city: 'berlin',
    chapter: 'TAG 1',
    codename: 'ABENDESSEN UM 20:00',
    title: 'Abendessen um 20:00',
    titleEn: 'Dinner at 20:00',
    time: '20:00',
    synopsis: 'Tobias Fink, Sportdirektor des FC Spree, will heute Abend eine Unterschrift. Dr. Kessler will eine korrekte. Sie sitzen dazwischen.',
    objectives: [
      { id: 'go', text: 'Fahren Sie zum Restaurant Lindner (Prenzlauer Berg)', location: 'restaurant' },
      { id: 'talk', text: 'Überstehen Sie den Small Talk', location: 'restaurant' },
      { id: 'negotiate', text: 'Sprechen Sie die Abweichungen an', location: 'restaurant' },
    ],
    targets: ['verhandeln', 'hoeflichkeit-k2', 'konnektoren', 'gen-prep', 'register-wechsel'],
    xp: 260,
    boss: true,
  },
  {
    id: 'm_amt',
    city: 'berlin',
    chapter: 'TAG 2',
    codename: 'DAS AMT',
    title: 'Das Amt',
    titleEn: 'The Office',
    time: '09:10',
    synopsis: 'Anmeldung innerhalb von 14 Tagen – Pflicht. Ohne Anmeldung keine Steuer-ID, ohne Steuer-ID kein Gehalt. Termin: heute, 09:10, Schalter 4.',
    objectives: [
      { id: 'go', text: 'Gehen Sie zum Bürgeramt', location: 'amt' },
      { id: 'register', text: 'Melden Sie Ihren Wohnsitz an', location: 'amt' },
    ],
    targets: ['passiv', 'nebensatz-verbend', 'hoeflichkeit-k2', 'n-deklination', 'verb-praep'],
    xp: 180,
  },
];

export const MISSION_BY_ID: Record<string, Mission> = Object.fromEntries(MISSIONS.map((m) => [m.id, m]));

/** Teasers for arcs in production (visible in the mission log, clearly marked). */
export const UPCOMING = [
  { codename: '48 STUNDEN', chapter: 'TAG 2–3', hook: 'Ein Journalist hat die polnische Vertragsfassung. Der Transfer steht auf der Kippe.' },
  { codename: 'MATCHDAY', chapter: 'TAG 3', hook: 'Stadion An der Spree. 22.000 Zuschauer. Ein Interview auf Deutsch – live.' },
  { codename: 'DIE VERHANDLUNG', chapter: 'TAG 4', hook: 'Der Berater will neu verhandeln. Auf Deutsch. Ohne Dr. Kessler.' },
];
