import type { NPC } from '../../engine/types';

export const NPCS: NPC[] = [
  {
    id: 'kasia',
    name: 'Katarzyna Nowicka',
    role: 'Vereidigte Übersetzerin · Freundin der Familie',
    roleGloss: 'tłumaczka przysięgła, przyjaciółka rodziny',
    personality: 'Warm, direkt, ehrgeizig für andere. Besteht darauf, dass Sie Deutsch sprechen – auch wenn Polnisch leichter wäre.',
    register: 'informal',
    voice: { pitch: 1.05, rate: 1, gender: 'f' },
    portrait: { hair: 'long', hairColor: '#3a2618', skin: '#e0b89a', coat: '#2c3440', accent: '#e8b04a' },
    bio: 'Lebt seit 14 Jahren in Berlin. Hat Ihnen die Wohnung und den Kontakt zur Kanzlei vermittelt. Ihr Satz: „Ab jetzt nur Deutsch.“',
    startRel: 40,
  },
  {
    id: 'pohl',
    name: 'Herr Pohl',
    role: 'DB-Service, Hauptbahnhof',
    roleGloss: 'obsługa kolei, dworzec główny',
    personality: 'Knapp, schnell, berlinerisch-effizient. Hilft gern – aber nur einmal.',
    register: 'formal',
    voice: { pitch: 0.8, rate: 1.1, gender: 'm' },
    portrait: { hair: 'cap', hairColor: '#8a8a8a', skin: '#e6c1a3', coat: '#b3141c', accent: '#ff5a4f' },
    bio: 'Seit 27 Jahren bei der Bahn. Hat alles gesehen. Wirklich alles.',
    startRel: 0,
  },
  {
    id: 'wiesner',
    name: 'Frau Wiesner',
    role: 'Vermieterin, Graefestraße 12',
    roleGloss: 'wynajmująca mieszkanie',
    personality: 'Korrekt, misstrauisch, detailverliebt. Wer höflich und pünktlich ist, gewinnt sie – langsam.',
    register: 'formal',
    voice: { pitch: 1.15, rate: 1.05, gender: 'f' },
    portrait: { hair: 'bob', hairColor: '#b9b4ab', skin: '#efd2bd', coat: '#5b4a3f', accent: '#d9c6a0', glasses: true },
    bio: 'Besitzt das Haus seit 1991. Hat eine Meinung zur Mülltrennung. Eine starke.',
    startRel: 0,
  },
  {
    id: 'emre',
    name: 'Emre Yıldız',
    role: 'Inhaber, Café Kiezbohne',
    roleGloss: 'właściciel kawiarni',
    personality: 'Schnell, witzig, Kreuzberger Urgestein. Duzt jeden ab der ersten Sekunde.',
    register: 'informal',
    voice: { pitch: 0.95, rate: 1.12, gender: 'm' },
    portrait: { hair: 'curly', hairColor: '#1a1410', skin: '#c89572', coat: '#2e3b2c', accent: '#ffb35c', beard: true },
    bio: 'Hat die Kiezbohne 2016 eröffnet. Kennt jeden im Graefekiez – und jedes Gerücht.',
    startRel: 10,
  },
  {
    id: 'lukas',
    name: 'Lukas Brandt',
    role: 'Associate, Kessler & Aydın',
    roleGloss: 'młodszy prawnik w kancelarii',
    personality: 'Locker, loyal, Fußball-verrückt. Berliner Schnauze mit Herz. Wird schnell zum Verbündeten.',
    register: 'informal',
    voice: { pitch: 1.0, rate: 1.15, gender: 'm' },
    portrait: { hair: 'short', hairColor: '#7a5230', skin: '#edc9ae', coat: '#20283a', accent: '#6fb7ff' },
    bio: 'Geboren in Marzahn, Jura an der HU. Hat eine Dauerkarte beim FC Spree. Sagt „icke“, wenn er müde ist.',
    startRel: 15,
  },
  {
    id: 'kessler',
    name: 'Dr. Jana Kessler',
    role: 'Partnerin, Kessler & Aydın Rechtsanwälte',
    roleGloss: 'partnerka kancelarii prawnej',
    personality: 'Präzise, schnell, fordernd, fair. Respektiert Kompetenz und Ehrlichkeit – verachtet Ausreden.',
    register: 'formal',
    voice: { pitch: 1.0, rate: 1.12, gender: 'f' },
    portrait: { hair: 'bun', hairColor: '#20160f', skin: '#e8c4a6', coat: '#15181f', accent: '#c8323a' },
    bio: 'Fachanwältin für Arbeitsrecht, Schwerpunkt Sportrecht. Hat drei Bundesliga-Vereine beraten. Spricht schneller, als die meisten denken.',
    startRel: 0,
  },
  {
    id: 'fink',
    name: 'Tobias Fink',
    role: 'Sportdirektor, FC Spree Berlin 1911',
    roleGloss: 'dyrektor sportowy klubu',
    personality: 'Charmant, kalkuliert, unter Druck. Wechselt aufs „du“, wenn er etwas will.',
    register: 'mixed',
    voice: { pitch: 0.9, rate: 1.08, gender: 'm' },
    portrait: { hair: 'short', hairColor: '#b8a27a', skin: '#e4bf9f', coat: '#23262d', accent: '#3ddc97' },
    bio: 'Ehemaliger Zweitliga-Profi. Hat den FC Spree in die erste Liga zurückgeführt. Transferfenster sind seine Jagdsaison.',
    startRel: 0,
  },
  {
    id: 'amt',
    name: 'Herr Schulze',
    role: 'Sachbearbeiter, Bürgeramt',
    roleGloss: 'urzędnik',
    personality: 'Ruhig, formell, unbestechlich. Fehlende Unterlagen sind fehlende Unterlagen.',
    register: 'formal',
    voice: { pitch: 0.85, rate: 1.0, gender: 'm' },
    portrait: { hair: 'bald', hairColor: '#555', skin: '#e9c9b0', coat: '#4a5058', accent: '#9fb3c8', glasses: true },
    bio: 'Bearbeitet 40 Anmeldungen am Tag. Lächelt bei Nummer 41.',
    startRel: 0,
  },
];

export const NPC_BY_ID: Record<string, NPC> = Object.fromEntries(NPCS.map((n) => [n.id, n]));
